[package]
name = "erl_aotc_parser"
version = "0.1.0"
authors = ["Dmytro Lytovchenko <dmytro.lytovchenko@gmail.com>"]

[dependencies]
erl_shared = {path = "../erl_shared"}
lalrpop-util = "0.15.2"
regex = "0.2.1"

[build-dependencies]
# A man has got to parse stuff
lalrpop = "0.15.2"
