# Run declaration checks through the default compiler action; syntax-only modes stay broader.
set(semantic_work "${WORK}/semantics")
file(MAKE_DIRECTORY "${semantic_work}")
function(semantic_case name source status pattern)
    file(WRITE "${semantic_work}/${name}.erl" "${source}")
    execute_process(COMMAND "${TOOL}" "${name}.erl" WORKING_DIRECTORY "${semantic_work}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err ENCODING UTF-8 TIMEOUT 15)
    if(NOT result STREQUAL "${status}" OR NOT out STREQUAL "" OR NOT err MATCHES "${pattern}")
        message(FATAL_ERROR "Semantic ${name}: ${result}: ${out}${err}")
    endif()
    if(EXISTS "${semantic_work}/a.out")
        message(FATAL_ERROR "Semantic analysis published an artifact")
    endif()
endfunction()
semantic_case(missing "f() -> 42." 1 "missing.erl:1:1.*missing module")
semantic_case(empty "" 1 "empty.erl:1:1.*missing module")
semantic_case(duplicate_module "-module(a). -module(b)." 1 "duplicate module")
semantic_case(duplicate_function "-module(a). f() -> 1. g() -> 2. f() -> 3." 1 "duplicate function f/0")
semantic_case(undefined_export "-module(a). -export([f/1]). f() -> 1." 1 "undefined function f/1")
semantic_case(duplicate_export "-module(a). -export([f/0,f/0]). f() -> 1." 1 "duplicate export f/0")
semantic_case(huge_export "-module(a). -export([f/99999999999999999999999])." 1 "arity must be in 0..255")
semantic_case(negative_export "-module(a). -export([f/-1])." 1 "negative_export.erl:1:28: bad attribute value")
semantic_case(unicode "-module('λ_mod'). -export(['quoted name'/0]). 'quoted name'() -> 42." 0 "^$")
semantic_case(overloads "-module(a). -export([f/0,f/1]). f() -> 1. f(X) -> X." 0 "^$")
execute_process(COMMAND "${TOOL}" --parse-check missing.erl WORKING_DIRECTORY "${semantic_work}"
    RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT err STREQUAL "")
    message(FATAL_ERROR "Syntax-only action performed semantic validation")
endif()
execute_process(COMMAND "${TOOL}" missing.erl undefined_export.erl WORKING_DIRECTORY "${semantic_work}"
    RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "missing module.*undefined function")
    message(FATAL_ERROR "Semantic failure prevented later-file diagnostics: ${err}")
endif()
semantic_case(empty_module "-module(''). f() -> 1." 1 "invalid module name")
set(parameters "")
foreach(index RANGE 0 255)
    if(index GREATER 0)
        string(APPEND parameters ",")
    endif()
    string(APPEND parameters "V${index}")
endforeach()
semantic_case(large_function "-module(a). f(${parameters}) -> 1." 1 "function arity exceeds 255")

semantic_case(supported_subset "-module(a). -export([f/2,id/1]). -author(\"a\"). -type box(T) :: {T}. -spec f(integer(), term()) -> integer(). f(X,_) -> g(X). g(Y) -> a:id(Y). id(Z) -> Z." 0 "^$")
semantic_case(atom_value "-module(a). f() -> ok." 1 "atom expressions")
semantic_case(float_value "-module(a). f() -> 1.5." 1 "heap expressions")
semantic_case(string_value "-module(a). f() -> \"a\"." 1 "heap expressions")
semantic_case(tuple_value "-module(a). f() -> {}." 1 "heap expressions")
semantic_case(list_value "-module(a). f() -> []." 1 "heap expressions")
semantic_case(binary_value "-module(a). f() -> <<1>>." 1 "heap expressions")
semantic_case(map_value "-module(a). f() -> #{}." 1 "heap expressions")
semantic_case(arithmetic "-module(a). f(X) -> X+1." 1 "arithmetic")
semantic_case(unary "-module(a). f(X) -> -X." 1 "arithmetic")
semantic_case(match "-module(a). f() -> X=1." 1 "pattern matching")
semantic_case(clauses "-module(a). f(X) -> X; f(Y) -> Y." 1 "multiple clauses")
semantic_case(pattern "-module(a). f(42) -> 1." 1 "pattern matching")
semantic_case(guard "-module(a). f(X) when is_integer(X) -> X." 1 "guards")
semantic_case(sequence "-module(a). f() -> 1, 2." 1 "expression sequences")
semantic_case(block "-module(a). f() -> begin 1 end." 1 "pattern matching")
semantic_case(case_expr "-module(a). f(X) -> case X of Y -> Y end." 1 "pattern matching")
semantic_case(if_expr "-module(a). f() -> if true -> 1 end." 1 "guards")
semantic_case(receive_expr "-module(a). f() -> receive X -> X end." 1 "receive")
semantic_case(send "-module(a). f(X) -> X ! 1." 1 "send expressions")
semantic_case(closure "-module(a). f() -> fun(X) -> X end." 1 "closures")
semantic_case(fun_reference "-module(a). f() -> fun f/0." 1 "closures")
semantic_case(remote_fun "-module(a). f() -> fun a:f/0." 1 "closures")
semantic_case(catch_expr "-module(a). f() -> catch g()." 1 "exceptions")
semantic_case(try_expr "-module(a). f() -> try 1 catch _:_ -> 2 end." 1 "exceptions")
semantic_case(maybe_expr "-module(a). f() -> maybe 1 end." 1 "pattern matching")
semantic_case(comprehension "-module(a). f(X) -> [Y || Y <- X]." 1 "heap expressions")
semantic_case(binary_comprehension "-module(a). f(X) -> << <<Y>> || Y <- X >>." 1 "heap expressions")
semantic_case(map_comprehension "-module(a). f(X) -> #{Y => Y || Y <- X}." 1 "heap expressions")
semantic_case(dynamic_call "-module(a). f(F) -> F(1)." 1 "dynamic calls")
semantic_case(dynamic_remote "-module(a). f(M) -> M:f()." 1 "dynamic calls")
semantic_case(remote_value "-module(a). f() -> a:f." 1 "dynamic calls")
semantic_case(record_value "-module(a). f() -> #r{}." 1 "heap expressions")
semantic_case(record_access "-module(a). f(X) -> X#r.a." 1 "heap expressions")
semantic_case(record_index "-module(a). f() -> #r.a." 1 "heap expressions")
semantic_case(compile_option "-module(a). -compile(export_all). f() -> 1." 1 "behavior-changing attributes")
semantic_case(transform "-module(a). -compile({parse_transform,x}). f() -> 1." 1 "behavior-changing attributes")
semantic_case(on_load "-module(a). -on_load(f/0). f() -> 1." 1 "behavior-changing attributes")
semantic_case(unknown_attribute "-module(a). -custom(1). f() -> 1." 1 "behavior-changing attributes")
semantic_case(parameterized "-module(a, [X]). f() -> 1." 1 "behavior-changing attributes")
semantic_case(import "-module(a). -import(b,[f/0]). g() -> 1." 1 "behavior-changing attributes")
semantic_case(unused "-module(a). -export([f/0]). f() -> 1. unused() -> ok." 1 "atom expressions")
semantic_case(bignum "-module(a). f() -> 99999999999999999999999999999." 1 "bignum expressions")
semantic_case(negative_bignum "-module(a). f() -> -99999999999999999999999999999." 1 "bignum expressions")
semantic_case(nested_bad "-module(a). f() -> g(h(1), ok)." 1 "atom expressions")
file(WRITE "${semantic_work}/unsupported.hrl" "bad() -> ok.\n")
semantic_case(include_origin "-module(a). -include(\"unsupported.hrl\")." 1 "unsupported.hrl:1:.*atom expressions")

if(WORD_BYTES EQUAL 8)
    set(minimum "-576460752303423488")
    set(maximum "576460752303423487")
    set(overflow "576460752303423488")
    set(underflow "-576460752303423489")
else()
    set(minimum "-134217728")
    set(maximum "134217727")
    set(overflow "134217728")
    set(underflow "-134217729")
endif()
semantic_case(minimum "-module(a). f() -> ${minimum}." 0 "^$")
semantic_case(maximum "-module(a). f() -> ${maximum}." 0 "^$")
semantic_case(overflow "-module(a). f() -> ${overflow}." 1 "bignum expressions")
semantic_case(underflow "-module(a). f() -> ${underflow}." 1 "bignum expressions")

semantic_case(feature_name "-module(a). f() -> ok." 1 "feature_name.erl:1:.*\\[atom expressions\\] notimpl")
file(WRITE "${semantic_work}/sentinel" "existing artifact")
execute_process(COMMAND "${TOOL}" -o sentinel supported_subset.erl unused.erl WORKING_DIRECTORY "${semantic_work}"
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
file(READ "${semantic_work}/sentinel" sentinel)
if(NOT result STREQUAL "1" OR NOT out STREQUAL "" OR NOT err MATCHES "\\[atom expressions\\] notimpl"
    OR NOT sentinel STREQUAL "existing artifact")
    message(FATAL_ERROR "Capability failure published output or lost its feature diagnostic: ${err}")
endif()

semantic_case(identity "-module(a). f(X) -> X." 0 "^$")
semantic_case(projection "-module(a). f(_, X, _) -> (X)." 0 "^$")
semantic_case(named_underscore "-module(a). f(_X) -> _X." 0 "^$")
semantic_case(unbound "-module(a). f(X) -> Missing." 1 "unbound variable Missing")
semantic_case(wildcard_read "-module(a). f(_) -> _." 1 "wildcard '_' cannot be read")
semantic_case(repeated_parameter "-module(a). f(X,X) -> X." 1 "\\[pattern matching\\] notimpl")
semantic_case(repeated_named_underscore "-module(a). f(_X,_X) -> 1." 1 "\\[pattern matching\\] notimpl")
semantic_case(binding_scope "-module(a). f(X) -> X. g(Y) -> X." 1 "unbound variable X")
semantic_case(nested_unbound "-module(a). f(X) -> g(X, h(Missing))." 1 "unbound variable Missing")
file(WRITE "${semantic_work}/binding.hrl" "f(X) -> Unbound.\n")
semantic_case(binding_include "-module(a). -include(\"binding.hrl\")." 1 "binding.hrl:1:.*unbound variable Unbound")
# Forward/remote calls resolve across positional files in one batch.
semantic_case(nested_local "-module(a). f() -> id(id(42)). id(X) -> X." 0 "^$")
semantic_case(forward_call "-module(a). f(X) -> g(X). g(Y) -> Y." 0 "^$")
semantic_case(missing_call "-module(a). f() -> absent()." 1 "undefined function a:absent/0")
semantic_case(call_arity "-module(a). f() -> g(1). g() -> 2." 1 "undefined function a:g/1")
semantic_case(private_self "-module(a). f() -> a:g(). g() -> 2." 1 "not exported")
semantic_case(unknown_module "-module(a). f() -> outside:g()." 1 "unknown module outside")
semantic_case(local_cycle "-module(a). f() -> g(). g() -> f()." 1 "recursive calls.*notimpl")
semantic_case(self_cycle "-module(a). f() -> f()." 1 "recursive calls.*notimpl")
file(WRITE "${semantic_work}/client.erl" "-module(client). -export([f/0]). f() -> server:id(server:value()).")
file(WRITE "${semantic_work}/server.erl" "-module(server). -export([id/1,value/0]). id(X) -> X. value() -> 42.")
execute_process(COMMAND "${TOOL}" client.erl server.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT err STREQUAL "")
 message(FATAL_ERROR "Batch forward remote resolution: ${err}")
endif()
file(WRITE "${semantic_work}/server.erl" "-module(server). -export([id/1,value/0]). id(X) -> X. value() -> client:f().")
execute_process(COMMAND "${TOOL}" client.erl server.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "recursive calls.*notimpl")
 message(FATAL_ERROR "Cross-module cycle: ${err}")
endif()
execute_process(COMMAND "${TOOL}" forward_call.erl identity.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "duplicate module in compilation batch")
 message(FATAL_ERROR "Duplicate batch module: ${err}")
endif()
file(WRITE "${semantic_work}/isolated.toml" "schema_version = 1\n[[targets]]\nname='client'\nsources = ['client.erl']\n[[targets]]\nname='server'\nsources = ['server.erl']\n")
execute_process(COMMAND "${TOOL}" --project isolated.toml WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "unknown module server" OR NOT err MATCHES "unknown module client")
 message(FATAL_ERROR "Project target isolation: ${err}")
endif()
file(WRITE "${semantic_work}/server.erl" "-module(server). -export([id/1,value/0]). id(X) -> X. value() -> 42.")
file(WRITE "${semantic_work}/batch.toml" "schema_version = 1\n[[targets]]\nname='combined'\nsources = ['client.erl', 'server.erl']\n")
execute_process(COMMAND "${TOOL}" --project batch.toml WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err STREQUAL "")
 message(FATAL_ERROR "Project batch resolution: ${out}${err}")
endif()
file(WRITE "${semantic_work}/call.hrl" "f() -> missing().\n")
semantic_case(call_include "-module(a). -include(\"call.hrl\")." 1 "call.hrl:1:.*undefined function a:missing/0")
semantic_case(remote_arity "-module(a). -export([f/0,g/0]). f() -> a:g(1). g() -> 1." 1 "undefined function a:g/1")
set(chain "-module(chain).\n")
foreach(index RANGE 0 499)
 math(EXPR next "${index}+1")
 string(APPEND chain "f${index}(X) -> f${next}(X).\n")
endforeach()
string(APPEND chain "f500(X) -> X.\n")
semantic_case(long_call_chain "${chain}" 0 "^$")
