# Run declaration checks through the default compiler action; syntax-only modes stay broader.
set(semantic_work "${WORK}/semantics")
file(MAKE_DIRECTORY "${semantic_work}")
function(semantic_case name source status pattern)
    file(WRITE "${semantic_work}/${name}.erl" "${source}")
    execute_process(COMMAND "${TOOL}" "${name}.erl" WORKING_DIRECTORY "${semantic_work}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err ENCODING UTF-8 TIMEOUT 15)
    if(NOT result STREQUAL "${status}" OR NOT out STREQUAL "" OR NOT err MATCHES "${pattern}")
        message(FATAL_ERROR "Semantic ${name}: ${result}: ${out}${err}")
    endif()
    if(EXISTS "${semantic_work}/a.out")
        message(FATAL_ERROR "Semantic analysis published an artifact")
    endif()
endfunction()
semantic_case(missing "f() -> 42." 1 "missing.erl:1:1.*missing module")
semantic_case(empty "" 1 "empty.erl:1:1.*missing module")
semantic_case(duplicate_module "-module(a). -module(b)." 1 "duplicate module")
semantic_case(duplicate_function "-module(a). f() -> 1. g() -> 2. f() -> 3." 1 "duplicate function f/0")
semantic_case(undefined_export "-module(a). -export([f/1]). f() -> 1." 1 "undefined function f/1")
semantic_case(duplicate_export "-module(a). -export([f/0,f/0]). f() -> 1." 1 "duplicate export f/0")
semantic_case(huge_export "-module(a). -export([f/99999999999999999999999])." 1 "arity must be in 0..255")
semantic_case(negative_export "-module(a). -export([f/-1])." 1 "negative_export.erl:1:28: bad attribute value")
semantic_case(unicode "-module('λ_mod'). -export(['quoted name'/0]). 'quoted name'() -> 42." 0 "^$")
semantic_case(overloads "-module(a). -export([f/0,f/1]). f() -> 1. f(X) -> X." 0 "^$")
semantic_case(map_exact_constructor "-module(a). f() -> #{a := 1}." 1 "map construction requires")
execute_process(COMMAND "${TOOL}" --parse-check missing.erl WORKING_DIRECTORY "${semantic_work}"
    RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT err STREQUAL "")
    message(FATAL_ERROR "Syntax-only action performed semantic validation")
endif()
execute_process(COMMAND "${TOOL}" missing.erl undefined_export.erl WORKING_DIRECTORY "${semantic_work}"
    RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "missing module.*undefined function")
    message(FATAL_ERROR "Semantic failure prevented later-file diagnostics: ${err}")
endif()
semantic_case(empty_module "-module(''). f() -> 1." 1 "invalid module name")
set(parameters "")
foreach(index RANGE 0 255)
    if(index GREATER 0)
        string(APPEND parameters ",")
    endif()
    string(APPEND parameters "V${index}")
endforeach()
semantic_case(large_function "-module(a). f(${parameters}) -> 1." 1 "function arity exceeds 255")

semantic_case(supported_subset "-module(a). -export([f/2,id/1]). -author(\"a\"). -type box(T) :: {T}. -spec f(integer(), term()) -> integer(). f(X,_) -> g(X). g(Y) -> a:id(Y). id(Z) -> Z." 0 "^$")
semantic_case(atom_value "-module(a). f() -> ok." 0 "^$")
semantic_case(float_value "-module(a). f() -> 1.5." 0 "")
semantic_case(string_value "-module(a). f() -> \"a\"." 0 "^$")
semantic_case(tuple_value "-module(a). f() -> {1}." 0 "^$")
semantic_case(list_value "-module(a). f() -> [1]." 0 "^$")
semantic_case(binary_value "-module(a). f() -> <<1>>." 0 "^$")
semantic_case(map_value "-module(a). f() -> #{}." 0 "^$")
semantic_case(arithmetic "-module(a). f(X) -> X+1." 0 "^$")
semantic_case(unary "-module(a). f(X) -> -X." 0 "^$")
semantic_case(match "-module(a). f() -> X=1." 0 "^$")
semantic_case(clauses "-module(a). f(X) -> X; f(Y) -> Y." 0 "")
semantic_case(pattern "-module(a). f({42}) -> 1." 0 "^$")
semantic_case(guard "-module(a). f(X) when is_integer(X,0,10) -> X." 0 "^$")
semantic_case(sequence "-module(a). f() -> 1, 2." 0 "^$")
semantic_case(block "-module(a). f() -> begin 1 end." 0 "^$")
semantic_case(case_expr "-module(a). f(X) -> case X of Y -> Y end." 0 "^$")
semantic_case(case_guard_call "-module(a). f(X) -> case X of Y when g(Y) -> Y end. g(Z) -> Z." 1
    "illegal guard call")
semantic_case(case_in_guard "-module(a). f(X) when case X of _ -> true end -> X." 1 "illegal guard expression")
semantic_case(if_expr "-module(a). f() -> if true -> 1 end." 0 "^$")
semantic_case(if_guard_call "-module(a). f(X) -> if g(X) -> X end. g(Z) -> Z." 1 "illegal guard call")
semantic_case(if_in_guard "-module(a). f(X) when if true -> true end -> X." 1 "illegal guard expression")
semantic_case(receive_expr "-module(a). f() -> receive X -> X end." 0 "^$")
semantic_case(receive_after "-module(a). f() -> receive X -> X after 0 -> 0 end." 0 "^$")
semantic_case(receive_after_bad_timeout "-module(a). f(X) -> receive after Y -> X end." 1 "unbound variable Y")
semantic_case(send "-module(a). f(X) -> X ! 1." 0 "^$")
semantic_case(closure "-module(a). f() -> fun(X) -> X end." 0 "^$")
semantic_case(named_fun "-module(a). f() -> fun F(X) -> F(X) end." 0 "^$")
semantic_case(named_fun_scope "-module(a). f() -> G = fun F(X) -> F(X) end, {G, F}." 1
    "named_fun_scope.erl:1:50: unbound variable F")
semantic_case(closure_unbound "-module(a). f() -> fun() -> Y end." 1 "closure_unbound.erl:1:29: unbound variable Y")
semantic_case(closure_scope "-module(a). f() -> F = fun() -> Y = 1 end, {F, Y}." 1 "closure_scope.erl:1:48: unbound variable Y")
semantic_case(closure_shadow "-module(a). -export([f/1]). f(X) -> G = fun(X) -> X end, G(X)." 0 "^$")
semantic_case(closure_heads "-module(a). f() -> fun(X) -> X; (X, Y) -> Y end." 1 "function head mismatch")
semantic_case(fun_reference "-module(a). f() -> fun f/0." 0 "^$")
semantic_case(remote_fun "-module(a). f() -> fun a:f/0." 0 "^$")
semantic_case(undefined_fun "-module(a). f() -> fun g/1." 1 "undefined_fun.erl:1:20: function g/1 undefined")
semantic_case(builtin_fun "-module(a). f() -> {fun is_atom/1, fun halt/1}." 0 "^$")
semantic_case(erlang_fun "-module(a). f() -> {fun erlang:abs/1, fun erlang:'+'/2, fun erlang:display/1}." 0 "^$")
semantic_case(builtin_fun_unbridged "-module(a). f() -> fun node/0." 1 "dynamic calls")
semantic_case(process_identities "-module(a). f() -> {self(), make_ref(), fun self/0, pid_to_list(self())}." 0 "^$")
semantic_case(spawn_builtins
    "-module(a). f() -> {spawn(fun() -> ok end), spawn(a, f, []), is_process_alive(self()), fun spawn/3}." 0 "^$")
semantic_case(link_builtins
    "-module(a). f(P) -> {spawn_link(fun() -> ok end), spawn_link(a, f, []), link(P), unlink(P), exit(P, x), exit_signal(P, x), process_flag(trap_exit, true), fun exit/2}." 0 "^$")
semantic_case(monitor_builtins
    "-module(a). f(P) -> R = monitor(process, P), {spawn_monitor(fun() -> ok end), demonitor(R), demonitor(R, [])}." 0 "^$")
semantic_case(self_guard "-module(a). f(X) when X =:= self() -> X." 1 "\\[guards\\] notimpl")
semantic_case(erlang_fun_unbridged "-module(a). f() -> fun erlang:apply/2." 1 "dynamic calls")
semantic_case(display_fun_local "-module(a). f() -> fun display/1." 1 "function display/1 undefined")
semantic_case(bridge_call "-module(a). f() -> {halt(), erlang:function_exported(a, f, 0)}." 0 "^$")
semantic_case(bridge_unqualified "-module(a). f() -> function_exported(a, f, 0)." 1
    "undefined function a:function_exported/3")
semantic_case(bridge_unknown "-module(a). f() -> erlang:no_such_builtin(1)." 1 "unknown module erlang")
semantic_case(list_operators "-module(a). f(X) -> {X ++ [1], X -- [1], setelement(1, {a}, X), tuple_to_list({X})}." 0 "^$")
semantic_case(list_operator_guard "-module(a). f(X) when X ++ [] =:= [] -> X." 1 "illegal guard expression")
semantic_case(conversions "-module(a). f(X) -> {atom_to_list(X), list_to_atom(X), integer_to_list(X, 16), float_to_list(X, [short]), iolist_to_binary(X)}." 0 "^$")
semantic_case(io_builtins "-module(a). f(X) -> {io:format(X), io:format(X, []), io:put_chars(X), fun io:format/2}." 0 "^$")
semantic_case(io_unknown "-module(a). f(X) -> io:fwrite(X)." 1 "unknown module io")
semantic_case(io_guard "-module(a). f(X) when io:format(X) =:= ok -> X." 1 "illegal guard")
semantic_case(make_tuple_unqualified "-module(a). f() -> make_tuple(1, a)." 1 "undefined function a:make_tuple/2")
semantic_case(variable_fun "-module(a). f(M) -> fun M:f/0." 0 "^$")
semantic_case(variable_fun_unbound "-module(a). f() -> fun M:f/0." 1 "variable_fun_unbound.erl:1:20: unbound variable M")
semantic_case(catch_expr "-module(a). f() -> catch g(). g() -> 1." 0 "^$")
semantic_case(catch_in_guard "-module(a). f(X) when catch X -> X." 1 "illegal guard expression")
semantic_case(catch_unsafe "-module(a). f(X) -> catch (Y = X), Y." 1 "unsafe variable Y")
semantic_case(try_expr "-module(a). f() -> try 1 of X -> X catch _:_ -> 2 end." 0 "^$")
semantic_case(try_unsafe "-module(a). f(X) -> try Y = X catch _ -> X end, Y." 1 "unsafe variable Y")
semantic_case(try_in_guard "-module(a). f(X) when try X catch _ -> X end -> X." 1 "illegal guard expression")
semantic_case(try_after "-module(a). f() -> try 1 of X -> X catch _ -> 2 after 3 end." 0 "^$")
semantic_case(try_after_unsafe "-module(a). f(X) -> try X after Y = X end, Y." 1 "unsafe variable Y")
semantic_case(try_stacktrace "-module(a). f() -> try 1 catch _:_:S -> S end." 0 "^$")
semantic_case(stack_bound "-module(a). f(S) -> try 1 catch _:_:S -> S end." 1
    "stacktrace variable S must not be previously bound")
semantic_case(stack_in_pattern "-module(a). f() -> try 1 catch _:S:S -> S end." 1
    "stacktrace variable S must not be previously bound")
semantic_case(stack_in_guard "-module(a). f() -> try 1 catch _:_:S when S =:= [] -> S end." 1
    "stacktrace variable S must not be used in a guard")
semantic_case(raise_stack "-module(a). f(S) -> erlang:raise(error, x, S)." 0 "^$")
semantic_case(raise_unqualified "-module(a). f(S) -> raise(error, x, S)." 1 "undefined function a:raise/3")
semantic_case(get_stacktrace "-module(a). f() -> erlang:get_stacktrace()." 1
    "erlang:get_stacktrace/0 is removed; use the new try/catch syntax")
semantic_case(maybe_expr "-module(a). f() -> maybe 1 end." 0 "^$")
semantic_case(maybe_else "-module(a). f(A) -> maybe {ok, X} ?= A, X else E when is_atom(E) -> E end." 0 "^$")
semantic_case(maybe_unsafe "-module(a). f(A) -> maybe {ok, X} ?= A end, X." 1 "unsafe variable X")
semantic_case(maybe_else_unsafe "-module(a). f(A) -> maybe {ok, X} ?= A else _ -> X end." 1 "unsafe variable X")
semantic_case(maybe_in_guard "-module(a). f(A) when maybe A end -> A." 1 "illegal guard expression")
semantic_case(maybe_disabled "-module(a). -feature(maybe_expr, disable). f(A) -> maybe ok ?= A end." 1
    "maybe_disabled.erl:1:58: expected form-ending dot")
semantic_case(comprehension "-module(a). f(X) -> [Y || Y <- X]." 0 "^$")
semantic_case(comprehension_shadow "-module(a). f(X, L) -> [X || X <- L]." 0 "^$")
semantic_case(comprehension_scope "-module(a). f(L) -> [X || X <- L], X." 1 "unbound variable X")
semantic_case(comprehension_zip_filter "-module(a). f(L) -> [X || X <- L && X > 1]." 1
    "only generators are allowed in a zip generator")
semantic_case(comprehension_assign "-module(a). f(L) -> [Y || X <- L, Y = X]." 1
    "matches using '=' are not allowed in comprehension qualifiers")
semantic_case(comprehension_assign_feature "-module(a). -feature(compr_assign, enable). f(L) -> [Y || X <- L, Y = X]."
    1 "heap expressions")
semantic_case(comprehension_in_guard "-module(a). f(L) when [X || X <- L] =:= [] -> L." 1 "illegal guard expression")
semantic_case(binary_generator "-module(a). f(B) -> [X || <<X>> <= B]." 0 "^$")
semantic_case(map_generator "-module(a). f(M) -> [{K, V} || K := V <- M]." 0 "^$")
semantic_case(map_exact_template "-module(a). f(L) -> #{X := X || X <- L}." 1
    "illegal map association, did you mean to use `=>`?")
semantic_case(binary_comprehension "-module(a). f(X) -> << <<Y>> || Y <- X >>." 0 "^$")
semantic_case(map_comprehension "-module(a). f(X) -> #{Y => Y || Y <- X}." 0 "^$")
semantic_case(fun_call "-module(a). f(F) -> F(1)." 0 "^$")
semantic_case(dynamic_remote "-module(a). f(M) -> M:f()." 0 "^$")
semantic_case(dynamic_function "-module(a). f(F) -> a:F(1)." 0 "^$")
semantic_case(apply_calls "-module(a). f(M, F) -> {apply(M, F, []), erlang:apply(fun f/2, [M, F])}." 0 "^$")
semantic_case(apply_guard "-module(a). f(X) when apply(X, []) -> X." 1 "illegal guard call")
semantic_case(local_apply "-module(a). f(X) -> apply(X, 1, 2). apply(A, B, C) -> {A, B, C}." 0 "^$")
semantic_case(remote_value "-module(a). f() -> a:f." 1 "dynamic calls")
semantic_case(record_value "-module(a). f() -> #r{}." 1 "heap expressions")
semantic_case(record_access "-module(a). f(X) -> X#r.a." 1 "heap expressions")
semantic_case(record_index "-module(a). f() -> #r.a." 1 "heap expressions")
semantic_case(record_update "-module(a). -record(r, {a, b}). f(X) -> X#r{a = Y = 1}, Y." 0 "^$")
semantic_case(record_update_unknown "-module(a). f(X) -> X#r{a = 1}." 1 "undefined record")
semantic_case(record_update_field "-module(a). -record(r, {a}). f(X) -> X#r{b = 1}." 1 "undefined record field b")
semantic_case(record_update_twice "-module(a). -record(r, {a}). f(X) -> X#r{a = 1, a = 2}." 1
    "duplicate record initializer")
semantic_case(record_update_wildcard "-module(a). -record(r, {a}). f(X) -> X#r{_ = 1}." 1
    "meaningless use of _ in update of record r")
semantic_case(record_update_sibling "-module(a). -record(r, {a, b}). f(X) -> X#r{a = Y = 1, b = Y}." 1
    "unbound variable Y")
semantic_case(record_update_guard "-module(a). -record(r, {a}). f(X) when X#r{a = 1} =:= X -> X." 1
    "illegal guard expression")
semantic_case(record_info "-module(a). -record(r, {a}). f() -> {record_info(fields, r), record_info(size, r)}." 0
    "^$")
semantic_case(record_info_selector "-module(a). -record(r, {a}). f() -> record_info(names, r)." 1
    "record_info_selector.erl:1:49: illegal record info")
semantic_case(record_info_variable "-module(a). -record(r, {a}). f(I) -> record_info(I, r)." 1 "illegal record info")
semantic_case(record_info_name "-module(a). f(N) -> record_info(fields, N)." 1 "illegal record info")
semantic_case(record_info_unknown "-module(a). f() -> record_info(fields, r)." 1
    "record_info/2 is only supported for tuple records")
semantic_case(record_info_later "-module(a). f() -> record_info(size, r). -record(r, {a})." 1
    "record_info/2 is only supported for tuple records")
semantic_case(record_info_native "-module(a). -record(#r{a}). f() -> record_info(size, r)." 1
    "record_info/2 is only supported for tuple records")
semantic_case(native_record "-module(a). -record #r{a = 1 + 2, b = [x | <<\"s\">>]}. f(X) -> {#r{}, X#r.zz, X#r{zz = 1}}."
    0 "^$")
semantic_case(native_default "-module(a). -record #r{a = foo()}. f() -> 1." 1
    "native_default.erl:1:[0-9]+: illegal default value for field a in native record r")
semantic_case(native_default_binary "-module(a). -record #r{a = <<1>>}. f() -> 1." 1
    "illegal default value for field a in native record r")
semantic_case(native_uninitialized "-module(a). -record #r{a, b}. f() -> #r{b = 1}." 1
    "field a is not initialized in native record r")
semantic_case(native_unknown_field "-module(a). -record #r{a}. f() -> #r{a = 1, zz = 2}." 1 "undefined record field zz")
semantic_case(native_index "-module(a). -record #r{a}. f() -> #r.a." 1 "syntax #r.a is only supported for tuple records")
semantic_case(native_wildcard "-module(a). -record #r{a = 1}. f() -> #r{_ = 2}." 1
    "multi-field initialization \\(assigning to _\\) is only supported for tuple records")
semantic_case(native_guard "-module(a). -record #r{a = 1}. f(X) when X =:= #r{} -> X." 1
    "creating a record in a guard is only supported for tuple records")
semantic_case(native_guard_update "-module(a). -record #r{a = 1}. f(X) when X#r{a = 2} =:= X -> X." 1
    "illegal guard expression")
semantic_case(export_record_late "-module(a). f() -> 1. -export_record([r]). -record #r{}." 1
    "attribute export_record after function definitions")
semantic_case(export_record_undefined "-module(a). -export_record([nope])." 1 "native record nope undefined")
semantic_case(export_record_tuple "-module(a). -export_record([t]). -record(t, {a})." 1
    "tuple records cannot be exported; only native records can")
semantic_case(export_record_form "-module(a). -export_record(foo)." 1
    "badly formed -export_record\\(\\); expected a list of record names")
semantic_case(import_record_defined "-module(a). -record #r{}. -import_record(m, [r])." 1
    "record r is already defined locally")
semantic_case(import_record_twice "-module(a). -import_record(m, [r]). -import_record(n, [r])." 1
    "record r already imported from m")
semantic_case(import_record_uses
    "-module(a). -import_record(m, [r]). f(X) when X#r.a =:= 1, is_record(X, r) -> X#r{a = 2}." 0 "^$")
semantic_case(qualified_wildcard "-module(a). f(X) -> X#m:r{_ = 1}." 1
    "multi-field initialization \\(assigning to _\\) is only supported for tuple records")
semantic_case(qualified_guard "-module(a). f(X) when X =:= #m:r{} -> X." 1
    "creating a record in a guard is only supported for tuple records")
semantic_case(anonymous_construction "-module(a). f() -> #_{a = 1}." 1 "native record '_' undefined")
semantic_case(anonymous_forms "-module(a). f(#_{a = A} = X) when X#_.a =:= 1 -> {A, X#_{a = 2}, X#_.b}." 0 "^$")
semantic_case(record_info_guard "-module(a). -record(r, {a}). f(X) when record_info(size, r) =:= X -> X." 1
    "illegal guard call")
semantic_case(record_info_defined "-module(a). -export([record_info/2]). record_info(A, B) -> {A, B}." 1
    "function record_info/2 already defined")
semantic_case(compile_option "-module(a). -compile(export_all). f() -> 1." 1 "behavior-changing attributes")
semantic_case(transform "-module(a). -compile({parse_transform,x}). f() -> 1." 1 "behavior-changing attributes")
semantic_case(compile_nowarn "-module(a). -compile([nowarn_deprecated_catch, nowarn_unused_function]). f() -> 1." 0 "^$")
semantic_case(on_load "-module(a). -on_load(f/0). f() -> 1." 1 "behavior-changing attributes")
semantic_case(unknown_attribute "-module(a). -custom(1). f() -> 1." 1 "behavior-changing attributes")
semantic_case(parameterized "-module(a, [X]). f() -> 1." 1 "behavior-changing attributes")
semantic_case(import "-module(a). -import(b,[f/0]). g() -> 1." 1 "behavior-changing attributes")
semantic_case(unused "-module(a). -export([f/0]). f() -> 1. unused() -> fun erlang:node/0." 1 "dynamic calls")
semantic_case(bignum "-module(a). f() -> 99999999999999999999999999999." 0 "^$")
semantic_case(negative_bignum "-module(a). f() -> -99999999999999999999999999999." 0 "^$")
semantic_case(nested_bad "-module(a). f(X) -> g(h(X), fun erlang:node/0)." 1 "dynamic calls")
file(WRITE "${semantic_work}/unsupported.hrl" "%% Unsupported.\nbad() -> fun erlang:node/0.\n")
semantic_case(include_origin "-module(a). -include(\"unsupported.hrl\")." 1 "unsupported.hrl:2:.*dynamic calls")

if(WORD_BYTES EQUAL 8)
    set(minimum "-576460752303423488")
    set(maximum "576460752303423487")
    set(overflow "576460752303423488")
    set(underflow "-576460752303423489")
else()
    set(minimum "-134217728")
    set(maximum "134217727")
    set(overflow "134217728")
    set(underflow "-134217729")
endif()
semantic_case(minimum "-module(a). f() -> ${minimum}." 0 "^$")
semantic_case(maximum "-module(a). f() -> ${maximum}." 0 "^$")
semantic_case(overflow "-module(a). f() -> ${overflow}." 0 "^$")
semantic_case(underflow "-module(a). f() -> ${underflow}." 0 "^$")

semantic_case(feature_name "-module(a). f() -> fun erlang:node/0." 1 "feature_name.erl:1:.*\\[dynamic calls\\] notimpl")
file(WRITE "${semantic_work}/sentinel" "existing artifact")
execute_process(COMMAND "${TOOL}" -o sentinel supported_subset.erl unused.erl WORKING_DIRECTORY "${semantic_work}"
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
file(READ "${semantic_work}/sentinel" sentinel)
if(NOT result STREQUAL "1" OR NOT out STREQUAL "" OR NOT err MATCHES "\\[dynamic calls\\] notimpl"
    OR NOT sentinel STREQUAL "existing artifact")
    message(FATAL_ERROR "Capability failure published output or lost its feature diagnostic: ${err}")
endif()

semantic_case(identity "-module(a). f(X) -> X." 0 "^$")
semantic_case(projection "-module(a). f(_, X, _) -> (X)." 0 "^$")
semantic_case(named_underscore "-module(a). f(_X) -> _X." 0 "^$")
semantic_case(unbound "-module(a). f(X) -> Missing." 1 "unbound variable Missing")
semantic_case(wildcard_read "-module(a). f(_) -> _." 1 "wildcard '_' cannot be read")
semantic_case(repeated_parameter "-module(a). f(X,X) -> X." 0 "^$")
semantic_case(repeated_named_underscore "-module(a). f(_X,_X) -> 1." 0 "^$")
semantic_case(binding_scope "-module(a). f(X) -> X. g(Y) -> X." 1 "unbound variable X")
semantic_case(nested_unbound "-module(a). f(X) -> g(X, h(Missing))." 1 "unbound variable Missing")
file(WRITE "${semantic_work}/binding.hrl" "f(X) -> Unbound.\n")
semantic_case(binding_include "-module(a). -include(\"binding.hrl\")." 1 "binding.hrl:1:.*unbound variable Unbound")
# Forward/remote calls resolve across positional files in one batch.
semantic_case(nested_local "-module(a). f() -> id(id(42)). id(X) -> X." 0 "^$")
semantic_case(forward_call "-module(a). f(X) -> g(X). g(Y) -> Y." 0 "^$")
semantic_case(missing_call "-module(a). f() -> absent()." 1 "undefined function a:absent/0")
semantic_case(call_arity "-module(a). f() -> g(1). g() -> 2." 1 "undefined function a:g/1")
semantic_case(private_self "-module(a). f() -> a:g(). g() -> 2." 1 "not exported")
semantic_case(unknown_module "-module(a). f() -> outside:g()." 1 "unknown module outside")
# Self and mutual recursion compile, including a component that can never return.
semantic_case(local_cycle "-module(a). f() -> g(). g() -> f()." 0 "^$")
semantic_case(self_cycle "-module(a). f() -> f()." 0 "^$")
file(WRITE "${semantic_work}/client.erl" "-module(client). -export([f/0]). f() -> server:id(server:value()).")
file(WRITE "${semantic_work}/server.erl" "-module(server). -export([id/1,value/0]). id(X) -> X. value() -> 42.")
execute_process(COMMAND "${TOOL}" client.erl server.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT err STREQUAL "")
 message(FATAL_ERROR "Batch forward remote resolution: ${err}")
endif()
file(WRITE "${semantic_work}/server.erl" "-module(server). -export([id/1,value/0]). id(X) -> X. value() -> client:f().")
execute_process(COMMAND "${TOOL}" client.erl server.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT err STREQUAL "")
 message(FATAL_ERROR "Cross-module cycle: ${err}")
endif()
execute_process(COMMAND "${TOOL}" forward_call.erl identity.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "duplicate module in compilation batch")
 message(FATAL_ERROR "Duplicate batch module: ${err}")
endif()
file(WRITE "${semantic_work}/isolated.toml" "schema_version = 1\n[[targets]]\nname='client'\nsources = ['client.erl']\n[[targets]]\nname='server'\nsources = ['server.erl']\n")
execute_process(COMMAND "${TOOL}" --project isolated.toml WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "unknown module server" OR NOT err MATCHES "unknown module client")
 message(FATAL_ERROR "Project target isolation: ${err}")
endif()
file(WRITE "${semantic_work}/server.erl" "-module(server). -export([id/1,value/0]). id(X) -> X. value() -> 42.")
file(WRITE "${semantic_work}/batch.toml" "schema_version = 1\n[[targets]]\nname='combined'\nsources = ['client.erl', 'server.erl']\n")
execute_process(COMMAND "${TOOL}" --project batch.toml WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err STREQUAL "")
 message(FATAL_ERROR "Project batch resolution: ${out}${err}")
endif()
file(WRITE "${semantic_work}/call.hrl" "f() -> missing().\n")
semantic_case(call_include "-module(a). -include(\"call.hrl\")." 1 "call.hrl:1:.*undefined function a:missing/0")
semantic_case(remote_arity "-module(a). -export([f/0,g/0]). f() -> a:g(1). g() -> 1." 1 "undefined function a:g/1")
set(chain "-module(chain).\n")
foreach(index RANGE 0 499)
 math(EXPR next "${index}+1")
 string(APPEND chain "f${index}(X) -> f${next}(X).\n")
endforeach()
string(APPEND chain "f500(X) -> X.\n")
semantic_case(long_call_chain "${chain}" 0 "^$")
semantic_case(type_forward "-module(a). -type a() :: b(). -type b() :: integer(). f() -> 1." 0 "^$")
semantic_case(type_recursive "-module(a). -type tree(T) :: nil | {T, tree(T)}. f() -> 1." 0 "^$")
semantic_case(type_mutual "-module(a). -type a() :: {b()}. -type b() :: a() | []." 0 "^$")
semantic_case(type_parameters "-module(a). -type box(T) :: {T,T}. -spec f(box(integer())) -> box(integer()). f(X) -> X." 0 "^$")
semantic_case(type_builtin_shadow "-module(a). -type integer() :: atom(). -type tuple() :: integer(). -type map() :: tuple(). -type use() :: map()." 0 "^$")
semantic_case(type_duplicate "-module(a). -type t() :: integer(). -type t() :: atom()." 1 "duplicate type declaration")
semantic_case(type_undefined "-module(a). -type t() :: absent()." 1 "undefined local type absent/0")
semantic_case(type_top_still_validates "-module(a). -type t() :: term() | absent()." 1 "undefined local type absent/0")
semantic_case(type_parameter_duplicate "-module(a). -type t(A,A) :: {A,A}." 0 "^$")
semantic_case(type_variable_scope "-module(a). -type t(A) :: {A,A}. -type u() :: A." 1 "singleton type variable A")
semantic_case(type_quantified "-module(a). -type pair() :: {A,A}." 0 "^$")
semantic_case(type_union_singleton "-module(a). -type t() :: A | A." 1 "singleton type variable A")
semantic_case(type_union_product "-module(a). -type t() :: {A,A} | A." 0 "^$")
semantic_case(type_union_parameter "-module(a). -type t(A) :: A | A." 0 "^$")
semantic_case(type_unused_parameter "-module(a). -type t(A) :: integer()." 1 "singleton type variable A")
semantic_case(type_remote_builtin "-module(a). -type t() :: erlang:integer()." 0 "^$")
semantic_case(type_erlang_external "-module(a). -type t() :: erlang:timestamp()." 0 "warning:.*unavailable external type metadata: erlang:timestamp")
semantic_case(type_self_builtin "-module(a). -type t() :: a:integer()." 0 "^$")
semantic_case(type_wrong_arity "-module(a). -type t() :: integer(atom())." 1 "undefined local type integer/1")
semantic_case(type_integer_budget "-module(a). -type t() :: (1 bsl 1000001)..(1 bsl 1000002)." 0 "warning:.*budget exhausted")
semantic_case(type_export_missing "-module(a). -export_type([missing/0])." 1 "export of undefined type")
semantic_case(type_export_duplicate "-module(a). -type t() :: integer(). -export_type([t/0,t/0])." 1 "duplicate type export")
semantic_case(type_export_bad "-module(a). -export_type(bad)." 1 "expected proper metadata list")
semantic_case(type_range_bad "-module(a). -type t() :: 10..1." 1 "increasing bounds")
semantic_case(type_range_equal "-module(a). -type t() :: 1..1." 1 "increasing bounds")
semantic_case(type_range_math "-module(a). -type t() :: (1 bsl 70)..((1 bsl 70)+10)." 0 "^$")
semantic_case(type_math_bad "-module(a). -type t() :: 1 div 0." 1 "invalid integer type expression")
semantic_case(type_bits_bad "-module(a). -type t() :: <<_:(-1)>>." 1 "nonnegative")
semantic_case(type_external "-module(a). -type t() :: unavailable:box(integer())." 0 "warning:.*unavailable external type metadata")
semantic_case(spec_missing "-module(a). -spec absent() -> integer()." 1 "specification for undefined function")
semantic_case(spec_duplicate "-module(a). -spec f() -> integer(). -spec f() -> integer(). f() -> 1." 1 "duplicate specification")
semantic_case(spec_wrong_module "-module(a). -spec other:f() -> integer(). f() -> 1." 1 "specification module differs")
semantic_case(spec_overload_arity "-module(a). -spec f(integer()) -> integer(); (integer(),integer()) -> integer(). f(X) -> X." 1 "overload arity mismatch")
semantic_case(spec_constraints "-module(a). -spec f(A) -> A when A :: integer(); (B) -> B when B :: atom(). f(X) -> X." 0 "^$")
semantic_case(spec_repeated_constraint "-module(a). -spec f(A) -> A when A :: integer(), A :: atom(). f(X) -> X." 0 "^$")
semantic_case(spec_constraint_scope "-module(a). -spec f(A) -> A when B :: integer(). f(X) -> X." 1 "singleton type variable B")
semantic_case(spec_overload_scope "-module(a). -spec f(A) -> integer(); (integer()) -> A. f(X) -> X." 1 "singleton type variable A")
semantic_case(spec_annotation "-module(a). -spec f(Input :: integer()) -> Output :: integer(). f(X) -> X." 0 "^$")
semantic_case(spec_narrow_does_not_guard "-module(a). -spec f(integer()) -> integer(). f(X) -> X." 0 "^$")
semantic_case(callback_optional "-module(a). -callback run(A) -> A. -optional_callbacks([run/1])." 0 "^$")
semantic_case(callback_missing "-module(a). -optional_callbacks([run/1])." 1 "optional callback is undefined")
semantic_case(callback_duplicate "-module(a). -callback run(A) -> A. -callback run(B) -> B." 1 "duplicate specification")
semantic_case(callback_optional_duplicate "-module(a). -callback run(A) -> A. -optional_callbacks([run/1,run/1])." 1 "duplicate optional callback")
semantic_case(record_type "-module(a). -record(r,{x :: integer()}). -type t() :: #r{x :: 1..10}." 0 "^$")
semantic_case(record_missing "-module(a). -type t() :: #missing{}." 1 "undefined record type")
semantic_case(record_field "-module(a). -record(r,{x}). -type t() :: #r{y :: integer()}." 1 "undefined record type field")
semantic_case(record_duplicate "-module(a). -record(r,{x}). -record(r,{y})." 1 "duplicate record declaration")
semantic_case(record_field_duplicate "-module(a). -record(r,{x,x})." 1 "duplicate record field")
semantic_case(record_refinement_duplicate "-module(a). -record(r,{x}). -type t() :: #r{x :: atom(),x :: integer()}." 1 "duplicate record type field")
file(WRITE "${semantic_work}/types.hrl" "-type t() :: missing().\n")
semantic_case(type_include "-module(a). -include(\"types.hrl\")." 1 "types.hrl:1:.*undefined local type missing/0")
file(WRITE "${semantic_work}/type_owner.erl" "-module(type_owner). -export_type([public/1,secret/0]). -type public(T) :: {T}. -opaque secret() :: integer(). -type private() :: integer().")
file(WRITE "${semantic_work}/type_user.erl" "-module(type_user). -type t() :: {type_owner:public(integer()),type_owner:secret()}.")
execute_process(COMMAND "${TOOL}" type_user.erl type_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT err STREQUAL "")
 message(FATAL_ERROR "Exported remote type resolution: ${err}")
endif()
file(WRITE "${semantic_work}/type_user.erl" "-module(type_user). -type t() :: type_owner:private().")
execute_process(COMMAND "${TOOL}" type_user.erl type_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "remote type is not exported")
 message(FATAL_ERROR "Private remote type accepted: ${err}")
endif()
file(WRITE "${semantic_work}/type_user.erl" "-module(type_user). -type t() :: type_owner:public().")
execute_process(COMMAND "${TOOL}" type_user.erl type_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "undefined remote type type_owner:public")
 message(FATAL_ERROR "Remote type arity mismatch accepted: ${err}")
endif()
file(WRITE "${semantic_work}/type_user.erl" "-module(type_user). -type t() :: type_owner:public(integer()).")
file(WRITE "${semantic_work}/types.toml" "schema_version = 1\n[[targets]]\nname='types'\nsources=['type_user.erl','type_owner.erl']\n")
execute_process(COMMAND "${TOOL}" --project types.toml WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err STREQUAL "")
 message(FATAL_ERROR "Project type batch resolution: ${out}${err}")
endif()
file(WRITE "${semantic_work}/types.toml" "schema_version = 1\n[[targets]]\nname='user'\nsources=['type_user.erl']\n[[targets]]\nname='owner'\nsources=['type_owner.erl']\n")
execute_process(COMMAND "${TOOL}" --project types.toml WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err MATCHES "unavailable external type metadata: type_owner:public")
 message(FATAL_ERROR "Type metadata leaked across project targets: ${out}${err}")
endif()
semantic_case(infer_bad_spec "-module(a). -spec f() -> atom(). f() -> 42." 0 "warning:.*inferred result contradicts specification for f")
semantic_case(infer_call_contract "-module(a). -spec id(atom()) -> atom(). id(X) -> X. f() -> id(42)." 0 "warning:.*inferred arguments contradict specification for id")
semantic_case(infer_overload "-module(a). -spec f(integer()) -> integer(); (atom()) -> atom(). f(_) -> 42." 0 "^$")
semantic_case(infer_constraint_unknown "-module(a). -spec id(A) -> A when A :: atom(). id(X) -> X. f() -> id(42)." 0 "^$")
semantic_case(infer_range "-module(a). -spec f() -> 1..10. f() -> -1." 0 "warning:.*inferred result contradicts")
semantic_case(infer_large_range "-module(a). -spec f() -> (-1 bsl 100)..(1 bsl 100). f() -> -42." 0 "^$")
semantic_case(infer_alias "-module(a). -type t() :: atom(). -spec f() -> t(). f() -> 1." 0 "warning:.*inferred result contradicts")
semantic_case(infer_recursive_unknown "-module(a). -type t() :: t(). -spec f() -> t(). f() -> 1." 0 "^$")
semantic_case(infer_nominal_unknown "-module(a). -nominal t() :: atom(). -spec f() -> t(). f() -> 1." 0 "^$")
semantic_case(infer_none "-module(a). -spec f() -> none(). f() -> 1." 0 "warning:.*inferred result contradicts")
semantic_case(infer_empty_domain "-module(a). -spec f(none()) -> atom(). f(_) -> 1." 0 "^$")
semantic_case(infer_nonnegative "-module(a). -spec f() -> non_neg_integer(). f() -> -1." 0 "warning:.*inferred result contradicts")
semantic_case(infer_byte "-module(a). -spec f() -> byte(). f() -> 256." 0 "warning:.*inferred result contradicts")
semantic_case(infer_valid_singleton "-module(a). -spec f() -> 42 | atom(). f() -> 42." 0 "^$")
file(WRITE "${semantic_work}/inference_owner.erl" "-module(inference_owner). -export([id/1,value/0]). id(X) -> X. value() -> 42.")
file(WRITE "${semantic_work}/inference_user.erl" "-module(inference_user). first() -> inference_owner:id(inference_owner:value()). second() -> inference_owner:id(-7). third(X) -> inference_owner:id(X). project(_,Y,_) -> Y. fourth() -> project(1,second(),1).")
execute_process(COMMAND "${TOOL}" --impldebug 23 inference_user.erl inference_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR
   NOT err MATCHES "inference_user.*first.*result=42" OR NOT err MATCHES "inference_user.*second.*result=-7" OR
   NOT err MATCHES "inference_user.*third.*result=argument\\[0\\]" OR NOT err MATCHES "inference_user.*fourth.*result=-7")
 message(FATAL_ERROR "Cross-module fresh inference: ${out}${err}")
endif()
set(inference_trace "${err}")
execute_process(COMMAND "${TOOL}" --impldebug 99 --impldebug 23,23 inference_user.erl inference_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err STREQUAL inference_trace)
 message(FATAL_ERROR "Repeated debug selection changed trace: ${out}${err}")
endif()
foreach(mode IN ITEMS plain other_step verbose parse)
 set(flags)
 if(mode STREQUAL other_step)
  set(flags --impldebug 99)
 elseif(mode STREQUAL verbose)
  set(flags --verbose)
 elseif(mode STREQUAL parse)
  set(flags --impldebug 23 --parse-check)
 endif()
 execute_process(COMMAND "${TOOL}" ${flags} inference_user.erl inference_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
 if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR err MATCHES "impldebug| inputs=")
  message(FATAL_ERROR "Unrequested inference output (${mode}): ${out}${err}")
 endif()
endforeach()
execute_process(COMMAND "${TOOL}" --impldebug 23 inference_user.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "unknown module inference_owner" OR err MATCHES "impldebug")
 message(FATAL_ERROR "Inference escaped its batch or ran after failure: ${err}")
endif()
file(WRITE "${semantic_work}/opaque_owner.erl" "-module(opaque_owner). -export([id/1]). -export_type([t/0]). -opaque t() :: atom(). -spec id(t()) -> t(). id(X) -> X.")
file(WRITE "${semantic_work}/opaque_user.erl" "-module(opaque_user). f() -> opaque_owner:id(42).")
execute_process(COMMAND "${TOOL}" opaque_user.erl opaque_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT err STREQUAL "")
 message(FATAL_ERROR "Contract check exposed a remote opaque: ${err}")
endif()
file(WRITE "${semantic_work}/inference_escape.erl" "-module('line\\nbreak'). 'quote\\\"name'() -> 42.")
execute_process(COMMAND "${TOOL}" --impldebug 23 inference_escape.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
string(FIND "${err}" "line\\x0abreak" escaped_module)
string(FIND "${err}" "quote\\x22name" escaped_function)
if(NOT result STREQUAL "0" OR escaped_module LESS 0 OR escaped_function LESS 0)
 message(FATAL_ERROR "Unescaped inference identities: ${err}")
endif()

execute_process(COMMAND "${TOOL}" --impldebug 24 inference_user.erl inference_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err MATCHES "impldebug 24.*first.*result=42")
 message(FATAL_ERROR "Step 24 inferred lowering input: ${out}${err}")
endif()

execute_process(COMMAND "${TOOL}" --impldebug 25 inference_user.erl inference_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err MATCHES "impldebug 25.*third.*result=argument")
 message(FATAL_ERROR "Step 25 inferred lowering input: ${out}${err}")
endif()

execute_process(COMMAND "${TOOL}" --impldebug 26 inference_user.erl inference_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err MATCHES "impldebug 26.*fourth.*result=-7")
 message(FATAL_ERROR "Step 26 inferred lowering input: ${out}${err}")
endif()

execute_process(COMMAND "${TOOL}" --impldebug 27 inference_user.erl inference_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result STREQUAL "0" OR NOT out STREQUAL "" OR NOT err MATCHES "impldebug 27.*first.*result=42")
 message(FATAL_ERROR "Step 27 inferred lowering input: ${out}${err}")
endif()
file(WRITE "${semantic_work}/lower_owner.erl" "-module(lower_owner). private() -> 42.")
file(WRITE "${semantic_work}/lower_client.erl" "-module(lower_client). f() -> lower_owner:private().")
execute_process(COMMAND "${TOOL}" lower_client.erl lower_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "not exported")
 message(FATAL_ERROR "Remote private callee accepted: ${err}")
endif()
file(WRITE "${semantic_work}/lower_client.erl" "-module(lower_client). f() -> lower_owner:missing().")
execute_process(COMMAND "${TOOL}" lower_client.erl lower_owner.erl WORKING_DIRECTORY "${semantic_work}" RESULT_VARIABLE result ERROR_VARIABLE err)
if(NOT result STREQUAL "1" OR NOT err MATCHES "undefined function lower_owner:missing/0")
 message(FATAL_ERROR "Remote missing callee accepted: ${err}")
endif()
