file(MAKE_DIRECTORY "${TEST_DIR}")
file(WRITE "${TEST_DIR}/source with spaces.erl" "-module(example).\n")
file(WRITE "${TEST_DIR}/-source.erl" "-module(example).\n")

function(check_cli name expected_exit expected_stdout expected_stderr)
    execute_process(COMMAND "${TOOL}" ${ARGN}
        WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err
    )
    if(NOT "${result}" STREQUAL "${expected_exit}")
        message(FATAL_ERROR "${name}: expected exit ${expected_exit}, got ${result}: ${err}")
    endif()
    if(NOT out MATCHES "${expected_stdout}" OR NOT err MATCHES "${expected_stderr}")
        message(FATAL_ERROR "${name}: unexpected stdout=[${out}] stderr=[${err}]")
    endif()
endfunction()

check_cli(help 0 "Usage: erlangaot" "^$" --help)
check_cli(short_help 0 "Usage: erlangaot" "^$" -h)
check_cli(version 0 "^erlangaot [0-9]+\\.[0-9]+\\.[0-9]+\n$" "^$" --version)
check_cli(no_inputs 2 "^$" "no input files")
check_cli(unknown_option 2 "^$" "unknown option" --unknown)
check_cli(missing_output 2 "^$" "expected a path after" -o)
check_cli(duplicate_output 2 "^$" "more than once" -o first -o second source.erl)
check_cli(help_with_bad_option 2 "^$" "unknown option" --help --unknown)
check_cli(help_with_missing_output 2 "^$" "expected a path after" --help --output)
check_cli(help_precedes_version 0 "Usage: erlangaot" "^$" --version --help)
check_cli(output_consumes_option_spelling 0 "Usage: erlangaot" "^$" -o --version --help)
check_cli(output_consumes_terminator 0 "Usage: erlangaot" "^$" --output -- --help)
check_cli(option_after_terminator_is_input 1 "^$" "cannot access|not a regular file" -- --help)
check_cli(missing_input 1 "^$" "cannot access|not a regular file" missing.erl)
check_cli(directory_input 1 "^$" "not a regular file" .)
check_cli(unimplemented 1 "^$" "compilation is not implemented" "source with spaces.erl")
check_cli(end_of_options 1 "^$" "compilation is not implemented" -- -source.erl)
check_cli(multiple_inputs 1 "^$" "compilation is not implemented"
    "source with spaces.erl" ./-source.erl)

set(output "${TEST_DIR}/output file")
file(REMOVE "${output}")
check_cli(no_output_created 1 "^$" "compilation is not implemented"
    --output "${output}" "source with spaces.erl")
if(EXISTS "${output}")
    message(FATAL_ERROR "Unimplemented compilation created an output file")
endif()
file(WRITE "${output}" "preserve existing output\n")
check_cli(no_output_overwritten 1 "^$" "compilation is not implemented"
    -o "${output}" "source with spaces.erl")
file(READ "${output}" contents)
if(NOT contents STREQUAL "preserve existing output\n")
    message(FATAL_ERROR "Unimplemented compilation modified an existing output file")
endif()

# Preprocessing checks consume source and options but never create executable output.
file(WRITE "${TEST_DIR}/warning.erl" "-module(warning). -warning({notice,1}).\n")
file(WRITE "${TEST_DIR}/error.erl" "-module(error). -error(stop).\n")
file(WRITE "${TEST_DIR}/defines.erl" "-module(defines). -if(?VALUE =:= {1,atom} andalso ?FLAG). ok. -else. -error(bad_define). -endif.\n")
file(WRITE "${TEST_DIR}/first.erl" "-module(first). -define(PRIVATE,1).\n")
file(WRITE "${TEST_DIR}/second.erl" "-module(second). -ifdef(PRIVATE). -error(leaked). -endif.\n")
file(MAKE_DIRECTORY "${TEST_DIR}/first include" "${TEST_DIR}/second include" "${TEST_DIR}/app/include")
file(WRITE "${TEST_DIR}/first include/pick.hrl" "-define(PICK,1).\n")
file(WRITE "${TEST_DIR}/second include/pick.hrl" "-define(PICK,2).\n")
file(WRITE "${TEST_DIR}/app/include/lib.hrl" "-define(LIB,true).\n")
file(WRITE "${TEST_DIR}/includes.erl" "-include(\"pick.hrl\"). -include_lib(\"demo/include/lib.hrl\"). -if(?PICK =:= 2 andalso ?LIB). ok. -else. -error(lookup). -endif.\n")
file(WRITE "${TEST_DIR}/features.erl" "-if(?FEATURE_ENABLED(compr_assign) andalso not ?FEATURE_ENABLED(maybe_expr)). ok. -else. -error(features). -endif.\n")
check_cli(preprocess 0 "^$" "^$" --preprocess-check "source with spaces.erl")
check_cli(preprocess_warning 0 "^$" "warning:.*notice" --preprocess-check warning.erl)
check_cli(preprocess_error 1 "^$" "error:.*stop" --preprocess-check error.erl)
check_cli(preprocess_definitions 0 "^$" "^$" --preprocess-check -D "VALUE={1,atom}" -DFLAG defines.erl)
check_cli(preprocess_invalid_definition 1 "^$" "literal Erlang term" --preprocess-check -DVALUE=1+2 first.erl)
check_cli(preprocess_duplicate_definition 1 "^$" "redefining macro" --preprocess-check -DA=1 -DA=2 first.erl)
check_cli(preprocess_isolation 0 "^$" "^$" --preprocess-check first.erl second.erl)
check_cli(preprocess_failure_latches 1 "^$" "stop" --preprocess-check error.erl first.erl)
check_cli(preprocess_includes 0 "^$" "^$" --preprocess-check -I "first include" "-Isecond include" --app-dir demo=app includes.erl)
check_cli(preprocess_features 0 "^$" "^$" --preprocess-check --enable-feature compr_assign --disable-feature maybe_expr features.erl)
check_cli(preprocess_unknown_feature 1 "^$" "unknown.*feature" --preprocess-check --enable-feature missing first.erl)
check_cli(preprocess_missing_include_operand 2 "^$" "expected a value" --preprocess-check -I)
check_cli(preprocess_bad_application 2 "^$" "expected app=directory" --preprocess-check --app-dir broken first.erl)
check_cli(preprocess_output_conflict 2 "^$" "cannot be used" --preprocess-check -o "${output}" first.erl)
file(WRITE "${TEST_DIR}/a.out" "existing executable\n")
check_cli(preprocess_preserves_output 0 "^$" "^$" --preprocess-check first.erl)
check_cli(print_pp_help 0 "--print-pp" "^$" --help)
check_cli(print_pp_no_input 2 "^$" "no input files" --print-pp)
check_cli(print_pp_missing_input 1 "^$" "cannot access|not a regular file" --print-pp missing.erl)
check_cli(print_pp_output_conflict 2 "^$" "cannot be used" --print-pp -o "${output}" first.erl)
check_cli(print_pp 0 "- module [(] example [)] [.]\n$" "^$" --print-pp "source with spaces.erl")
check_cli(print_pp_combined 0 "- module [(] example [)] [.]\n$" "^$"
    --preprocess-check --print-pp "source with spaces.erl")
check_cli(print_pp_warning 0 "- module [(] warning [)] [.]\n$" "warning:.*notice" --print-pp warning.erl)
check_cli(print_pp_failure_latches 1 "- module [(] first [)] [.]\n$" "error:.*stop"
    --print-pp error.erl first.erl)
check_cli(print_pp_isolation 0 "- module [(] first [)].*- module [(] second [)]" "^$"
    --print-pp first.erl second.erl)
file(WRITE "${TEST_DIR}/printing.erl" "-include(\"pick.hrl\"). -ifdef(FLAG). f() -> {?PICK, ?VALUE}. -else. -error(branch). -endif.\n")
check_cli(print_pp_expansion 0 "f [(] [)] -> [{] 2 , 42 [}] [.]\n$" "^$"
    --print-pp -I "first include" "-Isecond include" -DFLAG -DVALUE=42 printing.erl)
check_cli(print_pp_end_options 0 "- module [(] example [)]" "^$" --print-pp -- -source.erl)
file(READ "${TEST_DIR}/a.out" contents)
if(NOT contents STREQUAL "existing executable\n")
    message(FATAL_ERROR "Preprocessing overwrote executable output")
endif()
