# Close the original seed corpus with native AST evidence, independent of the OTP checkout.
file(GLOB records "${FIXTURES}/phase6/historical/*.ast")
foreach(record IN LISTS records)
    get_filename_component(stem "${record}" NAME_WE)
    set(input "${FIXTURES}/${stem}.erl")
    file(READ "${record}" expected)
    execute_process(COMMAND "${DUMP}" "${input}"
        RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 15)
    if(NOT status STREQUAL "0" OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Historical native AST mismatch: ${stem}: ${errors}")
    endif()
    if(LIVE)
        execute_process(COMMAND "${ESCRIPT}" "${HARNESS}" phase1 "${input}"
            RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 15)
        if(NOT status STREQUAL "0" OR NOT actual STREQUAL expected)
            message(FATAL_ERROR "Historical OTP AST mismatch: ${stem}: ${errors}")
        endif()
    endif()
endforeach()
execute_process(COMMAND "${DUMP}" "${FIXTURES}/bad.erl"
    RESULT_VARIABLE status OUTPUT_QUIET ERROR_VARIABLE errors TIMEOUT 15)
if(NOT status STREQUAL "1" OR NOT errors MATCHES "bad.erl:[0-9]+:[0-9]+")
    message(FATAL_ERROR "Historical bad source did not report a located source error")
endif()
# Every pinned inventory row must have a measured witness or the explicit SSA exclusion.
function(read_rows path output)
    # Literal Erlang semicolons must not become CMake list separators.
    file(READ "${path}" text)
    string(REPLACE ";" "<semicolon>" text "${text}")
    string(REPLACE "[" "<left-bracket>" text "${text}")
    string(REPLACE "]" "<right-bracket>" text "${text}")
    string(STRIP "${text}" text)
    string(REPLACE "\n" ";" rows "${text}")
    set(${output} "${rows}" PARENT_SCOPE)
endfunction()
read_rows("${FIXTURES}/grammar.tsv" grammar)
read_rows("${FIXTURES}/phase6/coverage.tsv" coverage)
list(LENGTH grammar expected_count)
list(LENGTH coverage actual_count)
if(NOT expected_count EQUAL actual_count)
    message(FATAL_ERROR "Coverage inventory lost grammar rows")
endif()
list(REMOVE_AT grammar 0)
list(REMOVE_AT coverage 0)
foreach(row witness IN ZIP_LISTS grammar coverage)
    string(REGEX MATCH "^[0-9]+" reference_line "${row}")
    if(NOT witness MATCHES "^${reference_line}\t(observed|excluded-ssa)\t([^\t]+)\t(.+)$")
        message(FATAL_ERROR "Missing/misaligned coverage: ${row}")
    endif()
    set(status "${CMAKE_MATCH_1}")
    set(path "${CMAKE_MATCH_2}")
    set(production "${CMAKE_MATCH_3}")
    string(REGEX REPLACE "^[^\t]+\t[^\t]+\t[^\t]+\t[^\t]+\t" "" expected_production "${row}")
    if(NOT production STREQUAL expected_production)
        message(FATAL_ERROR "Coverage production changed: ${reference_line}")
    endif()
    if(status STREQUAL "observed" AND NOT EXISTS "${FIXTURES}/${path}")
        message(FATAL_ERROR "Missing coverage witness: ${path}")
    endif()
    if(status STREQUAL "excluded-ssa" AND NOT row MATCHES "\texcluded\tSSA test annotation\t")
        message(FATAL_ERROR "Ordinary grammar cannot be excluded: ${row}")
    endif()
endforeach()
