# The pinned operation sequence preserves all 900 cases from std::mt19937 seed 0x29a016.
file(READ "${FIXTURES}/mutations.json" corpus)
file(MAKE_DIRECTORY "${WORK}")
string(JSON count LENGTH "${corpus}" cases)
if(NOT count EQUAL 900)
    message(FATAL_ERROR "The pinned mutation corpus must retain all 900 original operations")
endif()
math(EXPR last "${count}-1")
# Fast development runs keep every case; full runs repeat each to check determinism.
set(passes 2)
if("$ENV{ERLANG_AOT_TEST_MODE}" STREQUAL "fast")
    set(passes 1)
endif()
# A shard checks every SHARDS-th case starting at SHARD; without them one run checks all cases.
if(NOT DEFINED SHARDS)
    set(SHARD 0)
    set(SHARDS 1)
endif()
foreach(case RANGE ${SHARD} ${last} ${SHARDS})
    string(JSON seed GET "${corpus}" cases ${case} 0)
    string(JSON index GET "${corpus}" cases ${case} 1)
    string(JSON operation GET "${corpus}" cases ${case} 2)
    string(JSON length LENGTH "${corpus}" tokens ${seed})
    math(EXPR end "${length}-1")
    math(EXPR next "(${index}+1)%${end}")
    set(source "")
    foreach(position RANGE 0 ${end})
        set(selected ${position})
        if(operation EQUAL 0 AND position EQUAL index)
            continue()
        elseif(operation EQUAL 2)
            if(position EQUAL index)
                set(selected ${next})
            elseif(position EQUAL next)
                set(selected ${index})
            endif()
        endif()
        string(JSON token GET "${corpus}" tokens ${seed} ${selected})
        string(APPEND source "${token} ")
        if(operation EQUAL 1 AND position EQUAL index)
            string(APPEND source "${token} ")
        endif()
    endforeach()
    file(WRITE "${WORK}/mutation.erl" "${source}\nrecovered() -> ok.\n")
    foreach(pass RANGE 1 ${passes})
        # Each parse takes milliseconds; the generous hang guard tolerates fully loaded parallel CTest runs.
        execute_process(COMMAND "${TOOL}" --print-ast mutation.erl WORKING_DIRECTORY "${WORK}"
            RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30 ENCODING UTF-8)
        if(NOT status MATCHES "^[01]$" OR NOT output MATCHES "Function name=recovered arity=0 clauses=1")
            message(FATAL_ERROR "Mutation ${case} (seed ${seed}, token ${index}, op ${operation}): ${status}: ${error}")
        endif()
        set(record "${status}\n${output}\n${error}")
        if(pass EQUAL 1)
            set(first "${record}")
        elseif(NOT record STREQUAL first)
            message(FATAL_ERROR "Nondeterministic mutation ${case}")
        endif()
    endforeach()
endforeach()
