# Live reference replay is optional; offline coverage is a separate required test.
if(NOT EXISTS "${ESCRIPT}")
    message("SKIP: escript is unavailable")
    return()
endif()
file(GLOB sources "${FIXTURES}/*.erl")
foreach(source IN LISTS sources)
    get_filename_component(stem "${source}" NAME_WE)
    foreach(mode IN ITEMS raw epp lint)
        execute_process(COMMAND "${ESCRIPT}" "${HARNESS}" "${mode}" "${source}"
            RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
        if(result STREQUAL "77")
            message("SKIP: OTP 29.1 is required")
            return()
        endif()
        file(READ "${FIXTURES}/${stem}.${mode}" expected)
        if(NOT result STREQUAL "0" OR NOT actual STREQUAL expected)
            message(FATAL_ERROR "Parser reference mismatch: ${stem}/${mode}: ${errors}\n${actual}")
        endif()
    endforeach()
endforeach()
