# Compare reference records using the configured OTP 29+ installation.
if(NOT EXISTS "${ESCRIPT}")
    message(FATAL_ERROR "Configured escript is unavailable: ${ESCRIPT}")
endif()
file(GLOB sources "${FIXTURES}/*.erl")
foreach(source IN LISTS sources)
    get_filename_component(stem "${source}" NAME_WE)
    foreach(mode IN ITEMS raw epp lint)
        execute_process(COMMAND "${ESCRIPT}" "${HARNESS}" "${mode}" "${source}"
            RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
        file(READ "${FIXTURES}/${stem}.${mode}" expected)
        if(NOT result STREQUAL "0" OR NOT actual STREQUAL expected)
            message(FATAL_ERROR "Parser reference mismatch: ${stem}/${mode}: ${errors}\n${actual}")
        endif()
    endforeach()
endforeach()
