# Compare reference records using the configured OTP 29+ installation.
if(LIVE AND NOT EXISTS "${ESCRIPT}")
    message(FATAL_ERROR "Configured escript is unavailable: ${ESCRIPT}")
endif()
if(NOT DEFINED PHASE)
    set(PHASE phase2)
endif()
file(GLOB_RECURSE inputs "${FIXTURES}/${PHASE}/*.erl" "${FIXTURES}/${PHASE}/*.reject")
foreach(input IN LISTS inputs)
    execute_process(COMMAND "${DUMP}" "${input}"
        RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE errors)
    if(input MATCHES "\\.reject$")
        set(mode accept)
        set(expected "rejected\n")
        if(NOT status STREQUAL "1")
            message(FATAL_ERROR "Expected native rejection: ${input}: ${status} ${errors}")
        endif()
    else()
        set(mode phase1)
        file(READ "${input}.ast" expected)
        if(NOT status STREQUAL "0" OR NOT actual STREQUAL expected)
            message(FATAL_ERROR "Native AST mismatch: ${input}: ${errors}\n${actual}")
        endif()
    endif()
    if(LIVE)
        execute_process(COMMAND "${ESCRIPT}" "${HARNESS}" "${mode}" "${input}"
            RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
        if(NOT status STREQUAL "0" OR NOT actual STREQUAL expected)
            message(FATAL_ERROR "OTP mismatch: ${input}: ${errors}\n${actual}")
        endif()
        if(EXISTS "${input}.lint")
            file(READ "${input}.lint" lint_expected)
            execute_process(COMMAND "${ESCRIPT}" "${HARNESS}" lint "${input}"
                RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
            if(NOT status STREQUAL "0" OR NOT actual STREQUAL lint_expected)
                message(FATAL_ERROR "OTP lint mismatch: ${input}: ${errors}\n${actual}")
            endif()
        endif()
    endif()
endforeach()
