# Native AST parity with pinned OTP records runs offline; live replay is an optional addition.
if(LIVE AND NOT EXISTS "${ESCRIPT}")
    message("SKIP: escript is unavailable")
    return()
endif()
foreach(stem IN ITEMS minimal expanded phase1)
    file(READ "${FIXTURES}/${stem}.phase1" expected)
    execute_process(COMMAND "${DUMP}" "${FIXTURES}/${stem}.erl"
        RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors)
    if(NOT result STREQUAL "0" OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Native Phase I AST mismatch: ${stem}: ${errors}\n${actual}")
    endif()
    if(LIVE)
        execute_process(COMMAND "${ESCRIPT}" "${HARNESS}" phase1 "${FIXTURES}/${stem}.erl"
            RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
        if(result STREQUAL "77")
            message("SKIP: OTP 29.1 is required")
            return()
        endif()
        if(NOT result STREQUAL "0" OR NOT actual STREQUAL expected)
            message(FATAL_ERROR "OTP Phase I AST mismatch: ${stem}: ${errors}\n${actual}")
        endif()
    endif()
endforeach()
