# Compare reference records using the configured OTP 29+ installation.
if(LIVE AND NOT EXISTS "${ESCRIPT}")
    message(FATAL_ERROR "Configured escript is unavailable: ${ESCRIPT}")
endif()
if(NOT DEFINED PHASE)
    set(PHASE phase2)
endif()
if(PHASE STREQUAL "phase5")
    # The supplemental index closes implementation rows without rewriting pinned records.
    file(STRINGS "${FIXTURES}/phase5/coverage.tsv" coverage)
    list(REMOVE_AT coverage 0)
    foreach(row IN LISTS coverage)
        string(REPLACE "\t" "|" columns "${row}")
        string(REGEX REPLACE "^[^|]*[|][^|]*[|][^|]*[|]([^|]*)[|].*$" "\\1" paths "${columns}")
        string(REPLACE "," ";" paths "${paths}")
        foreach(path IN LISTS paths)
            if(NOT EXISTS "${FIXTURES}/phase5/${path}")
                message(FATAL_ERROR "Missing Phase V coverage fixture: ${path}")
            endif()
        endforeach()
    endforeach()
endif()
file(GLOB_RECURSE inputs "${FIXTURES}/${PHASE}/*.erl" "${FIXTURES}/${PHASE}/*.reject" "${FIXTURES}/${PHASE}/*.builder-reject")
foreach(input IN LISTS inputs)
    execute_process(COMMAND "${DUMP}" "${input}"
        RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE errors)
    if(input MATCHES "[.-]reject$")
        set(mode accept)
        set(expected "rejected\n")
        if(input MATCHES "\\.builder-reject$")
            set(mode builder_exception)
            set(expected "builder_exception\n")
        endif()
        if(NOT status STREQUAL "1")
            message(FATAL_ERROR "Expected native rejection: ${input}: ${status} ${errors}")
        endif()
    else()
        set(mode phase1)
        file(READ "${input}.ast" expected)
        if(NOT status STREQUAL "0" OR NOT actual STREQUAL expected)
            message(FATAL_ERROR "Native AST mismatch: ${input}: ${errors}\n${actual}")
        endif()
    endif()
    if(LIVE)
        execute_process(COMMAND "${ESCRIPT}" "${HARNESS}" "${mode}" "${input}"
            RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
        if(NOT status STREQUAL "0" OR NOT actual STREQUAL expected)
            message(FATAL_ERROR "OTP mismatch: ${input}: ${errors}\n${actual}")
        endif()
        if(EXISTS "${input}.lint")
            file(READ "${input}.lint" lint_expected)
            execute_process(COMMAND "${ESCRIPT}" "${HARNESS}" lint "${input}"
                RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE errors TIMEOUT 10)
            if(NOT status STREQUAL "0" OR NOT actual STREQUAL lint_expected)
                message(FATAL_ERROR "OTP lint mismatch: ${input}: ${errors}\n${actual}")
            endif()
        endif()
    endif()
endforeach()
