# Offline scanner parity and integrity checks always run without Erlang.
file(STRINGS "${FIXTURES}/SHA256SUMS" records)
foreach(record IN LISTS records)
    string(SUBSTRING "${record}" 0 64 expected)
    string(SUBSTRING "${record}" 66 -1 name)
    file(SHA256 "${FIXTURES}/${name}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Reference record changed without regeneration: ${name}")
    endif()
endforeach()
file(GLOB sources "${FIXTURES}/*.erl")
foreach(source IN LISTS sources)
    get_filename_component(stem "${source}" NAME_WE)
    execute_process(COMMAND "${DUMP}" "${source}" RESULT_VARIABLE result OUTPUT_VARIABLE actual)
    file(READ "${FIXTURES}/${stem}.tokens" expected)
    if(NOT result STREQUAL "0" OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Parser-corpus scanner mismatch: ${stem}")
    endif()
endforeach()
file(READ "${FIXTURES}/minimal.raw" good)
file(READ "${FIXTURES}/bad.raw" bad)
file(READ "${FIXTURES}/lint_only.raw" syntax)
file(READ "${FIXTURES}/lint_only.lint" lint)
if(NOT good MATCHES "integer,0,42" OR NOT bad MATCHES "error,erl_parse"
   OR syntax MATCHES "error,erl_parse" OR NOT lint MATCHES "lint,error")
    message(FATAL_ERROR "Reference acceptance classifications are inconsistent")
endif()
