file(MAKE_DIRECTORY "${WORK}")

# Inspect complete observable results while bounding both time and printer output growth.
function(stress name source expected_status pattern)
    file(WRITE "${WORK}/${name}.erl" "${source}")
    execute_process(COMMAND "${TOOL}" --print-ast "${name}.erl" WORKING_DIRECTORY "${WORK}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15 ENCODING UTF-8)
    string(LENGTH "${output}" size)
    if(NOT status STREQUAL "${expected_status}" OR NOT "${output}${error}" MATCHES "${pattern}" OR size GREATER 6000000)
        message(FATAL_ERROR "${name}: ${status}: ${error}")
    endif()
endfunction()
string(REPEAT "+1" 12000 chain)
stress(operator_chain "f() -> 0${chain}." 0 "\\[depth=12000\\].*right: IntegerLiteral value=1\n$")
string(REPEAT "/1" 12000 divisions)
stress(attribute_recovery "-custom(f${divisions}). good() -> ok." 1 "Function name=good.*error:")
string(REPEAT "X = " 2000 matches)
stress(match_depth "f() -> ${matches}1." 1 "nesting budget exhausted")
string(REPEAT "{" 3000 opens)
string(REPEAT "}" 3000 closes)
stress(tuple_depth "f() -> ${opens}ok${closes}." 1 "nesting budget exhausted")
string(REPEAT ",ok" 8192 elements)
stress(wide_list "f() -> [ok${elements}]." 0 "count=8193")
string(REPEAT ",true" 4096 qualifiers)
stress(wide_qualifiers "f() -> [x || true${qualifiers}]." 0 "qualifiers=4097")
string(REPEAT "#{a => 1}" 4096 maps)
stress(postfix_maps "f() -> M${maps}." 0 "\\[depth=4096\\]")
string(REPEAT ",1" 4096 segments)
stress(wide_binary "f() -> <<1${segments}>>." 0 "segments=4097")
string(REPEAT "-unknown" 4096 modifiers)
stress(wide_modifiers "f() -> <<1/integer${modifiers}>>." 0 "modifiers=4097")
string(REPEAT "<<" 1000 opens)
string(REPEAT ">>" 1000 closes)
stress(binary_depth "f() -> ${opens}1${closes}." 1 "nesting budget exhausted")
