# Name modules after their contents so ordering, deduplication and selection are observable.
set(tree "${WORK}/discovery[base]")
file(MAKE_DIRECTORY "${tree}/src/nested/empty" "${tree}/fallback" "${tree}/later")
foreach(name IN ITEMS a b .hidden)
    string(REPLACE "." "" module "${name}")
    file(WRITE "${tree}/src/${name}.erl" "-module(${module}). value() -> ok.\n")
endforeach()
file(WRITE "${tree}/src/nested/c.erl" "-module(c). value() -> ok.\n")
file(WRITE "${tree}/src/header.hrl" "not Erlang")
file(WRITE "${tree}/src/upper.ERL" "not Erlang")
file(WRITE "${tree}/src/λ.erl" "-module(unicode). value() -> ok.\n")

# Reuse the real CLI checker while varying only manifest selection fields.
function(selection name fields expected)
    file(WRITE "${tree}/${name}.toml" "schema_version=1\n[[targets]]\nname='app'\n${fields}\n")
    execute_process(COMMAND "${TOOL}" --project "${tree}/${name}.toml" --print-ast
        WORKING_DIRECTORY "${outside}" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 15)
    string(REGEX MATCHALL "ModuleAttribute name=[a-z]+" modules "${out}")
    string(REPLACE "ModuleAttribute name=" "" modules "${modules}")
    if(NOT code STREQUAL "0" OR NOT err STREQUAL "" OR NOT modules STREQUAL expected)
        message(FATAL_ERROR "${name}: ${code}: expected ${expected}, got ${modules}: ${err}")
    endif()
endfunction()
selection(direct "sources=['src/*.erl']" "hidden;a;b;unicode")
selection(recursive "sources=['src/**/*.erl']" "hidden;a;b;c;unicode")
selection(directory "source_dirs=['src']" "hidden;a;b;c;unicode")
selection(double_recursive "sources=['src/**/**/c.erl']" "c")
selection(one_scalar "sources=['src/?.erl']" "a;b;unicode")
selection(overlap "sources=['src/b.erl','src/*.erl','src/../src/b.erl']\nsource_dirs=['src']" "b;hidden;a;unicode;c")
selection(empty_directory "sources=['src/a.erl']\nsource_dirs=['src/nested/empty']" "a")
file(WRITE "${tree}/wildcards/abcz.erl" "-module(wildcard).\n")
selection(star_then_scalar "sources=['wildcards/a*?z.erl']" "wildcard")
file(WRITE "${tree}/case.toml" "schema_version=1\n[[targets]]\nname='app'\nsources=['src/A*.erl']\n")
check(case_sensitive_pattern 1 "^$" "source" "${tree}/case.toml" --print-ast)

foreach(pattern IN ITEMS "missing*.erl" "[a].erl" "{a,b}.erl" "!a.erl" "a**.erl")
    file(WRITE "${tree}/bad.toml" "schema_version=1\n[[targets]]\nname='app'\nsources=['${pattern}']\n")
    check(bad_glob 1 "^$" "bad.toml.*sources" "${tree}/bad.toml" --print-ast)
endforeach()
file(WRITE "${tree}/bad.toml" "schema_version=1\n[[targets]]\nname='app'\nsource_dirs=['absent']\n")
check(missing_directory 1 "^$" "source directory" "${tree}/bad.toml" --print-ast)
file(WRITE "${tree}/bad.toml" "schema_version=1\n[[targets]]\nname='app'\nsource_dirs=['src/nested/empty']\n")
check(empty_selection 1 "^$" "source" "${tree}/bad.toml" --print-ast)

file(WRITE "${tree}/fallback/space λ.erl" "-module(fallback). value() -> ok.\n")
file(WRITE "${tree}/later/space λ.erl" "-module(later). value() -> ok.\n")
set(search "[targets.options]\nsource_search_paths=['absent','fallback','later']")
selection(fallback "sources=['space λ.erl']\n${search}" "fallback")
file(WRITE "${tree}/space λ.erl" "-module(direct). value() -> ok.\n")
selection(primary "sources=['space λ.erl']\n${search}" "direct")
file(WRITE "${outside}/absolute.erl" "-module(absolute).\n")
selection(absolute "sources=['${outside}/absolute.erl']" "absolute")
selection(normalized_directory "source_dirs=['fallback/../later']" "later")
file(MAKE_DIRECTORY "${tree}/blocked.erl")
file(WRITE "${tree}/fallback/blocked.erl" "-module(fallback).\n")
file(WRITE "${tree}/blocked.toml" "schema_version=1\n[[targets]]\nname='app'\nsources=['blocked.erl']\n${search}\n")
check(blocked_fallback 1 "^$" "not an accessible regular file" "${tree}/blocked.toml" --print-ast)

# Filesystem capabilities are reported individually; unsupported links do not hide other cases.
file(CREATE_LINK "${tree}/src/b.erl" "${tree}/hard.erl" RESULT hard)
if(hard STREQUAL "0")
    selection(hard_alias "sources=['src/b.erl','hard.erl']" "b")
    file(WRITE "${tree}/outputs.toml" "schema_version=1\n[[targets]]\nname='app'\nsources=['src/a.erl']\noutput='src/b.erl'\n[[targets]]\nname='tests'\nsources=['src/a.erl']\noutput='hard.erl'\n")
    check(output_identity_collision 1 "^$" "output" "${tree}/outputs.toml")
    file(READ "${tree}/src/b.erl" unchanged)
    if(NOT unchanged STREQUAL "-module(b). value() -> ok.\n")
        message(FATAL_ERROR "Output preflight changed an existing file")
    endif()
else()
    message(STATUS "SKIP capability: hard links: ${hard}")
endif()
file(CREATE_LINK "${tree}/src/a.erl" "${tree}/link.erl" SYMBOLIC RESULT symbolic)
if(symbolic STREQUAL "0")
    selection(link_alias "sources=['src/a.erl','link.erl']" "a")
    file(CREATE_LINK "${tree}/absent.erl" "${tree}/dangling.erl" SYMBOLIC RESULT dangling)
    if(dangling STREQUAL "0")
        file(WRITE "${tree}/dangling.toml" "schema_version=1\n[[targets]]\nname='app'\nsources=['dangling*.erl']\n")
        check(dangling_link 1 "^$" "source" "${tree}/dangling.toml" --print-ast)
    else()
        message(STATUS "SKIP capability: dangling symlinks: ${dangling}")
    endif()
else()
    message(STATUS "SKIP capability: file symlinks: ${symbolic}")
endif()
file(CREATE_LINK "${tree}/src" "${tree}/src/nested/cycle" SYMBOLIC RESULT cycle)
if(cycle STREQUAL "0")
    selection(cycle "source_dirs=['src']" "hidden;a;b;c;unicode")
    file(CREATE_LINK "${tree}" "${outside}/linked" SYMBOLIC RESULT base_link)
    if(base_link STREQUAL "0")
        check(linked_manifest_base 0 "ModuleAttribute name=direct" "^$" "${outside}/linked/primary.toml" --print-ast)
    else()
        message(STATUS "SKIP capability: symlinked manifest base: ${base_link}")
    endif()
else()
    message(STATUS "SKIP capability: directory symlinks: ${cycle}")
endif()
if(EXISTS "${tree}/SRC/a.erl")
    set(case_alias TRUE)
    selection(case_alias "sources=['src/a.erl','SRC/a.erl']" "a")
else()
    set(case_alias FALSE)
    message(STATUS "SKIP capability: case aliases on case-sensitive filesystem")
endif()
message(STATUS "Filesystem capabilities (0=available): hardlink=${hard}, file_symlink=${symbolic}, dangling=${dangling}, directory_cycle=${cycle}, linked_base=${base_link}, case_alias=${case_alias}")

# A real multi-source corpus checks deterministic publication and target isolation.
foreach(index RANGE 0 127)
    file(WRITE "${tree}/corpus/module${index}.erl" "-module(corpus). value() -> ${index}.\n")
endforeach()
file(WRITE "${tree}/corpus/deep/leaf/last.erl" "-module(last).\n")
file(WRITE "${tree}/corpus.toml" "schema_version=1\n[[targets]]\nname='app'\nsources=['corpus/**/*.erl']\n[[targets]]\nname='tests'\nsource_dirs=['corpus']\n")
foreach(pass RANGE 1 2)
    execute_process(COMMAND "${TOOL}" --project "${tree}/corpus.toml" --print-ast
        RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
    string(REGEX MATCHALL "ModuleAttribute name=" modules "${out}")
    list(LENGTH modules count)
    if(NOT code STREQUAL "0" OR NOT err STREQUAL "" OR NOT count EQUAL 258)
        message(FATAL_ERROR "Corpus processing failed: ${code}: ${count}: ${err}")
    endif()
    if(pass EQUAL 1)
        set(first "${out}")
    elseif(NOT first STREQUAL out)
        message(FATAL_ERROR "Corpus output is nondeterministic")
    endif()
endforeach()
