file(REMOVE_RECURSE "${WORK}")
set(project "${WORK}/project with spaces λ")
set(outside "${WORK}/outside")
file(MAKE_DIRECTORY "${project}" "${outside}/cli-include")
file(COPY "${FIXTURES}/" DESTINATION "${project}")
file(WRITE "${outside}/cli-include/choice.hrl" "-define(PICK,99).\n")
file(READ "${project}/project.toml" original)

# Invoke the real CLI from an unrelated working directory and inspect its streams.
function(check name code stdout stderr manifest)
    execute_process(COMMAND "${TOOL}" --project "${manifest}" ${ARGN}
        WORKING_DIRECTORY "${outside}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT "${result}" STREQUAL "${code}" OR NOT out MATCHES "${stdout}" OR NOT err MATCHES "${stderr}")
        message(FATAL_ERROR "${name}: exit=${result} stdout=[${out}] stderr=[${err}]")
    endif()
endfunction()
check(all 0 "^$" "^$" "${project}/project.toml" --parse-check)
check(subset 0 "^$" "^$" "${project}/project.toml" --preprocess-check --target tests)
check(values 0 "IntegerLiteral value=101.*IntegerLiteral value=11.*IntegerLiteral value=202" "^$"
    "${project}/project.toml" --print-ast)
check(cli_include_base 0 "IntegerLiteral value=99" "^$"
    "${project}/project.toml" --print-ast --target app -I cli-include)
execute_process(COMMAND "${TOOL}" --project project.toml --parse-check
    WORKING_DIRECTORY "${project}" RESULT_VARIABLE local_result OUTPUT_VARIABLE local_out ERROR_VARIABLE local_err)
if(NOT local_result EQUAL 0 OR NOT local_out STREQUAL "" OR NOT local_err STREQUAL "")
    message(FATAL_ERROR "Invocation from the project directory failed")
endif()
foreach(pass RANGE 1 2)
    execute_process(COMMAND "${TOOL}" --project "${project}/project.toml" --print-ast
        WORKING_DIRECTORY "${outside}" RESULT_VARIABLE result OUTPUT_VARIABLE text ERROR_VARIABLE err)
    if(NOT result EQUAL 0 OR NOT err STREQUAL "")
        message(FATAL_ERROR "Repeated AST run failed: ${err}")
    endif()
    if(pass EQUAL 1)
        set(first "${text}")
    elseif(NOT first STREQUAL text)
        message(FATAL_ERROR "Project AST output is nondeterministic")
    endif()
endforeach()
file(WRITE "${project}/unselected.toml" "${original}\n[[targets]]\nname='absent'\nsources=['absent/no.erl']\n")
check(unselected_missing 0 "^$" "^$" "${project}/unselected.toml" --parse-check --target app)
check(preflight 1 "^$" "cannot find source" "${project}/unselected.toml" --print-ast)
file(APPEND "${project}/unselected.toml" "bogus=true\n")
check(unselected_schema 1 "^$" "unknown key" "${project}/unselected.toml" --print-ast --target app)
string(REPLACE "\"VALUE=101\"" "\"VALUE=101\", \"FAIL\"" failed "${original}")
file(WRITE "${project}/failure.toml" "${failed}")
check(aggregate 1 "IntegerLiteral value=202" "target app.*injected_app_failure" "${project}/failure.toml" --print-ast)
file(WRITE "${project}/build/app" "preserve executable\n")
check(backend 1 "^$" "compilation is not implemented" "${project}/project.toml")
check(check_preserves 0 "^$" "^$" "${project}/project.toml" --parse-check)
file(READ "${project}/build/app" after)
if(NOT after STREQUAL "preserve executable\n" OR EXISTS "${project}/build/tests")
    message(FATAL_ERROR "Project processing modified output destinations")
endif()
# Quoted native arguments and manifest strings must retain literal semicolons.
set(semidir "${WORK}/semi;project")
file(COPY "${project}/" DESTINATION "${semidir}")
file(WRITE "${semidir}/semi;source.erl" "-module(semi). value() -> ok.\n")
string(REPLACE "sources = [" "sources = [\"semi;source.erl\", " semimanifest "${original}")
file(WRITE "${semidir}/project.toml" "${semimanifest}")
execute_process(COMMAND "${TOOL}" --project "${semidir}/project.toml" --parse-check
    WORKING_DIRECTORY "${outside}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 0 OR NOT out STREQUAL "" OR NOT err STREQUAL "")
    message(FATAL_ERROR "Semicolon paths failed: ${err}")
endif()
