[package]
name = "erl_aotc"
version = "0.1.0"
authors = ["Dmytro Lytovchenko <dmytro.lytovchenko@gmail.com>"]

[dependencies]
erl_aotc_parser = {path = "../erl_aotc_parser"}
erl_shared = {path = "../erl_shared"}
# A man has got to emit LLVM IR
llvm-sys = "60"
# matches = "*"
