"""Compile-time diagnostics compared with OTP: each directory of tests/fixtures/lint is a case whose golden.json lists
its files in compile order (authored) and the errors and warnings OTP's compiler reports for them (generated by
regenerate.py). Clause compiles the files as one batch and must report the same diagnostics, in any order.

    lint.py <clau> [case...]
"""
import hashlib
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
CASES = ROOT / 'tests/fixtures/lint'
GOLDEN = 'golden.json'
# One Clause diagnostic line: `warning: file:line:column: message`.
DIAGNOSTIC = re.compile(r'^(warning|error): ([^:]+):(\d+):(\d+): (.*)$')


def digest(path):
    """Hashes file bytes with CRLF normalized to LF so checkouts agree across hosts."""
    return hashlib.sha256(path.read_bytes().replace(b'\r\n', b'\n')).hexdigest()


def names():
    """Lists case directories, each identified by its golden file."""
    return sorted(path.parent.name for path in CASES.glob(f'*/{GOLDEN}'))


def load(case):
    """Reads a case golden and checks its authored fields."""
    golden = json.loads((CASES / case / GOLDEN).read_text(encoding='utf8'))
    assert golden.get('schema') == 1, f'{case}: golden schema must be 1'
    assert golden.get('files'), f'{case}: golden needs files'
    return golden


def inputs(case, golden):
    """Hashes every listed file, which together determine the golden."""
    return {name: digest(CASES / case / name) for name in golden['files']}


def normalized(diagnostics):
    """Diagnostics as sorted (file, line, column, severity, message) tuples."""
    return sorted((d['file'], d['line'], d['column'], d['severity'], d['message']) for d in diagnostics)


def observe(tool, case, golden):
    """Clause's exit status and diagnostics for the case's files."""
    result = subprocess.run([tool, *golden['files']], cwd=CASES / case, capture_output=True, encoding='utf8',
                            timeout=300, check=False)
    diagnostics = []
    for line in result.stderr.splitlines():
        if match := DIAGNOSTIC.match(line):
            diagnostics.append({'file': match[2], 'line': int(match[3]), 'column': int(match[4]),
                                'severity': match[1], 'message': match[5]})
        elif diagnostics and line and not line.startswith(' '):
            # A message of several lines continues on the next ones, as OTP's do.
            diagnostics[-1]['message'] += '\n' + line
    return result.returncode, diagnostics


def check(tool, case):
    """Problems with one case: a stale golden, a different exit status or different diagnostics."""
    golden = load(case)
    if 'diagnostics' not in golden or golden.get('inputs') != inputs(case, golden):
        return [f'{case}: golden is missing or stale; run tests/compiler/lint/regenerate.py']
    status, diagnostics = observe(tool, case, golden)
    expected, actual = normalized(golden['diagnostics']), normalized(diagnostics)
    problems = [] if status == golden['exit_status'] else [f'{case}: exit {status}, OTP {golden["exit_status"]}']
    problems += [f'{case}: missing {item}' for item in expected if item not in actual]
    problems += [f'{case}: unexpected {item}' for item in actual if item not in expected]
    return problems


def main():
    tool, selected = str(pathlib.Path(sys.argv[1]).resolve()), sys.argv[2:] or names()
    problems = [problem for case in selected for problem in check(tool, case)]
    for problem in problems:
        print(problem)
    print(f'lint: {len(selected)} cases, {len(problems)} problem(s)')
    sys.exit(1 if problems else 0)


if __name__ == '__main__':
    main()
