# Check the real service bridge emits one failure line, and keeps success/error propagation quiet.
foreach(mode IN ITEMS quiet missing unavailable)
    set(arguments)
    if(NOT mode STREQUAL "quiet")
        list(APPEND arguments "${mode}")
    endif()
    execute_process(COMMAND "${PROGRAM}" ${arguments} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output STREQUAL "")
        message(FATAL_ERROR "Bridge ${mode} failed: ${result}: ${output}${error}")
    endif()
    if(mode STREQUAL "quiet")
        if(NOT error STREQUAL "")
            message(FATAL_ERROR "Successful/ordinary failing calls emitted diagnostics: ${error}")
        endif()
    elseif(NOT error MATCHES "^\\[builtins\\] notimpl[^\n]*\n$")
        message(FATAL_ERROR "Expected exactly one unavailable diagnostic: ${error}")
    endif()
endforeach()
