# Every reachable service owner emits exactly one stderr line; lifecycle and tests using sinks stay silent.
set(modes quiet term allocate collect send run execute unload builtin nested)
set(features "" "term services" "allocation" "garbage collection" "message passing"
    "scheduling" "process execution" "dynamic modules" "builtins" "garbage collection")
foreach(mode feature IN ZIP_LISTS modes features)
    execute_process(COMMAND "${PROGRAM}" "${mode}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error)
    set(expected 1)
    if(mode STREQUAL "quiet")
        set(expected 0)
    endif()
    if(NOT result EQUAL expected OR NOT output STREQUAL "")
        message(FATAL_ERROR "Service ${mode} failed: ${result}: ${output}${error}")
    endif()
    if(mode STREQUAL "quiet")
        if(NOT error STREQUAL "")
            message(FATAL_ERROR "Lifecycle called a deferred service: ${error}")
        endif()
    elseif(NOT error MATCHES "^\\[${feature}\\] notimpl[^\n]*\n$")
        message(FATAL_ERROR "Expected one ${feature} report: ${error}")
    endif()
endforeach()
execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT output STREQUAL "" OR NOT error STREQUAL "")
    message(FATAL_ERROR "Injected-sink tests were not silent: ${result}: ${output}${error}")
endif()
