#pragma once
#include <array>
#include <cstdint>
#include <string_view>

namespace erlang_aot::abi::v1 {
// Stable IDs are explicit and never recycled; names describe deferred semantics, not generic errors.
enum class FeatureId : std::uint8_t {
    // Reserve zero for a missing/unrecognized feature; it never has a catalog entry.
    invalid = 0,
    pattern_matching = 1,
    guards = 2,
    multiple_clauses = 3,
    arithmetic = 4,
    bignum_expressions = 5,
    atom_expressions = 6,
    heap_expressions = 7,
    dynamic_calls = 8,
    recursive_calls = 9,
    closures = 10,
    exceptions = 11,
    receive = 12,
    behavior_attributes = 13,
    term_services = 14,
    builtins = 15,
    process_execution = 16,
    message_passing = 17,
    scheduling = 18,
    allocation = 19,
    garbage_collection = 20,
    atom_collection = 21,
    dynamic_modules = 22,
    executable_linking = 23
};
enum class FeatureOwner : std::uint8_t { compiler, runtime, driver };
enum class FeatureStatus : std::uint8_t { deferred };

struct FeatureInfo {
    // Keep machine identity and diagnostic spelling stable across unrelated implementations.
    FeatureId id;
    std::string_view name;
    // Identify the sole reporter; callers propagate its failure without formatting it again.
    FeatureOwner owner;
    std::string_view boundary;
    // Record current availability and the plan step that installs the owning handler.
    FeatureStatus status;
    unsigned plan_step;
    // Name the focused CTest that exercises this entry's reporting contract.
    std::string_view failure_test;
};

// Catalog reservations do not install handlers or expand the executable language subset.
inline constexpr std::array feature_catalog{
    FeatureInfo{.id = FeatureId::pattern_matching,
                .name = "pattern matching",
                .owner = FeatureOwner::compiler,
                .boundary = "capability/pattern analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::guards,
                .name = "guards",
                .owner = FeatureOwner::compiler,
                .boundary = "capability/guard analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::multiple_clauses,
                .name = "multiple clauses",
                .owner = FeatureOwner::compiler,
                .boundary = "capability/clause analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::arithmetic,
                .name = "arithmetic",
                .owner = FeatureOwner::compiler,
                .boundary = "expression lowering",
                .status = FeatureStatus::deferred,
                .plan_step = 24,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::bignum_expressions,
                .name = "bignum expressions",
                .owner = FeatureOwner::compiler,
                .boundary = "integer capability analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::atom_expressions,
                .name = "atom expressions",
                .owner = FeatureOwner::compiler,
                .boundary = "literal capability analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::heap_expressions,
                .name = "heap expressions",
                .owner = FeatureOwner::compiler,
                .boundary = "aggregate capability analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::dynamic_calls,
                .name = "dynamic calls",
                .owner = FeatureOwner::compiler,
                .boundary = "call capability analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::recursive_calls,
                .name = "recursive calls",
                .owner = FeatureOwner::compiler,
                .boundary = "batch call graph analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 19,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::closures,
                .name = "closures",
                .owner = FeatureOwner::compiler,
                .boundary = "fun capability analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::exceptions,
                .name = "exceptions",
                .owner = FeatureOwner::compiler,
                .boundary = "exception capability analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::receive,
                .name = "receive",
                .owner = FeatureOwner::compiler,
                .boundary = "receive capability analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::behavior_attributes,
                .name = "behavior-changing attributes",
                .owner = FeatureOwner::compiler,
                .boundary = "attribute capability analysis",
                .status = FeatureStatus::deferred,
                .plan_step = 16,
                .failure_test = "codegen_features"},
    FeatureInfo{.id = FeatureId::term_services,
                .name = "term services",
                .owner = FeatureOwner::runtime,
                .boundary = "TermFactory constructors",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_services"},
    FeatureInfo{.id = FeatureId::builtins,
                .name = "builtins",
                .owner = FeatureOwner::runtime,
                .boundary = "native callable invocation",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_services"},
    FeatureInfo{.id = FeatureId::process_execution,
                .name = "process execution",
                .owner = FeatureOwner::runtime,
                .boundary = "SchedulerService::execute",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_services"},
    FeatureInfo{.id = FeatureId::message_passing,
                .name = "message passing",
                .owner = FeatureOwner::runtime,
                .boundary = "ProcessContext::send",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_services"},
    FeatureInfo{.id = FeatureId::scheduling,
                .name = "scheduling",
                .owner = FeatureOwner::runtime,
                .boundary = "SchedulerService::run",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_services"},
    FeatureInfo{.id = FeatureId::allocation,
                .name = "allocation",
                .owner = FeatureOwner::runtime,
                .boundary = "ProcessHeap::allocate",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_services"},
    FeatureInfo{.id = FeatureId::garbage_collection,
                .name = "garbage collection",
                .owner = FeatureOwner::runtime,
                .boundary = "ProcessHeap::collect",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_services"},
    FeatureInfo{.id = FeatureId::atom_collection,
                .name = "atom collection",
                .owner = FeatureOwner::runtime,
                .boundary = "AtomStorage::collect",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_features"},
    FeatureInfo{.id = FeatureId::dynamic_modules,
                .name = "dynamic modules",
                .owner = FeatureOwner::runtime,
                .boundary = "CodeServer::unload",
                .status = FeatureStatus::deferred,
                .plan_step = 14,
                .failure_test = "runtime_services"},
    FeatureInfo{.id = FeatureId::executable_linking,
                .name = "executable linking",
                .owner = FeatureOwner::driver,
                .boundary = "driver final executable output",
                .status = FeatureStatus::deferred,
                .plan_step = 35,
                .failure_test = "codegen_features"},
};

// Unknown IDs are invalid inputs, never an invented future feature or a successful fallback.
constexpr const FeatureInfo *find_feature(FeatureId id) noexcept {
    for (const auto &feature : feature_catalog) {
        if (feature.id == id) {
            return &feature;
        }
    }
    return nullptr;
}
} // namespace erlang_aot::abi::v1
