# Windows LLVM links static zstd; prefer an installation and otherwise build it locally.
include("${CMAKE_CURRENT_LIST_DIR}/../ZstdDependencies.cmake")
foreach(variable IN ITEMS zstd_INCLUDE_DIR zstd_LIBRARY_RELEASE zstd_LIBRARY_DEBUG)
    if(DEFINED ERLANG_AOT_AUTOMATIC_${variable} AND "${${variable}}" STREQUAL "${ERLANG_AOT_AUTOMATIC_${variable}}")
        unset(${variable} CACHE)
        unset(${variable})
    endif()
endforeach()
find_path(zstd_INCLUDE_DIR zstd.h HINTS "${zstd_ROOT}" ENV zstd_ROOT PATH_SUFFIXES include)
find_library(zstd_LIBRARY_RELEASE NAMES zstd_static HINTS "${zstd_ROOT}" ENV zstd_ROOT PATH_SUFFIXES lib)
find_library(zstd_LIBRARY_DEBUG NAMES zstd_staticd HINTS "${zstd_ROOT}" ENV zstd_ROOT PATH_SUFFIXES lib)
if(NOT zstd_INCLUDE_DIR OR NOT (zstd_LIBRARY_RELEASE OR zstd_LIBRARY_DEBUG))
    if(NOT ERLANG_AOT_DOWNLOAD_ZSTD)
        message(FATAL_ERROR "Static zstd is required by LLVM. Set zstd_ROOT to an MSVC installation or enable ERLANG_AOT_DOWNLOAD_ZSTD.")
    endif()
    erlang_aot_build_zstd(prefix)
    set(zstd_INCLUDE_DIR "${prefix}/include" CACHE PATH "zstd headers" FORCE)
    set(zstd_LIBRARY_RELEASE "${prefix}/lib/zstd_static.lib" CACHE FILEPATH "Release zstd" FORCE)
    set(zstd_LIBRARY_DEBUG "${prefix}/lib/zstd_staticd.lib" CACHE FILEPATH "Debug zstd" FORCE)
    foreach(variable IN ITEMS zstd_INCLUDE_DIR zstd_LIBRARY_RELEASE zstd_LIBRARY_DEBUG)
        set(ERLANG_AOT_AUTOMATIC_${variable} "${${variable}}" CACHE INTERNAL "Automatic zstd selection" FORCE)
    endforeach()
endif()
include(SelectLibraryConfigurations)
select_library_configurations(zstd)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(zstd REQUIRED_VARS zstd_LIBRARY zstd_INCLUDE_DIR)
if(zstd_FOUND AND NOT TARGET zstd::libzstd_static)
    add_library(zstd::libzstd_static STATIC IMPORTED)
    set_target_properties(zstd::libzstd_static PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${zstd_INCLUDE_DIR}")
    # Unlisted configurations (for example RelWithDebInfo) should prefer the Release CRT.
    foreach(configuration IN ITEMS RELEASE DEBUG)
        if(zstd_LIBRARY_${configuration})
            set_property(TARGET zstd::libzstd_static APPEND PROPERTY IMPORTED_CONFIGURATIONS ${configuration})
            set_property(TARGET zstd::libzstd_static PROPERTY IMPORTED_LOCATION_${configuration} "${zstd_LIBRARY_${configuration}}")
        endif()
    endforeach()
endif()
