# LLVM calls FindZLIB while loading its package; keep the fallback local to that search.
include("${CMAKE_CURRENT_LIST_DIR}/../ZlibDependencies.cmake")
if(ERLANG_AOT_ZLIB_ROOT_HINT)
    set(ZLIB_ROOT "${ERLANG_AOT_ZLIB_ROOT_HINT}")
endif()
if(NOT DEFINED ZLIB_USE_STATIC_LIBS)
    set(ZLIB_USE_STATIC_LIBS ON)
endif()

# Probe quietly first, retaining the caller's required/version semantics for the final lookup.
function(erlang_aot_probe_zlib)
    set(ZLIB_FIND_REQUIRED FALSE)
    set(ZLIB_FIND_QUIETLY TRUE)
    include("${CMAKE_ROOT}/Modules/FindZLIB.cmake")
    set(ZLIB_FOUND "${ZLIB_FOUND}" PARENT_SCOPE)
endfunction()

# Re-evaluate automatic builds when the parent toolchain or LLVM CRT choice changes.
foreach(variable IN ITEMS ZLIB_INCLUDE_DIR ZLIB_LIBRARY_DEBUG ZLIB_LIBRARY_RELEASE)
    if(DEFINED ERLANG_AOT_AUTOMATIC_${variable} AND "${${variable}}" STREQUAL "${ERLANG_AOT_AUTOMATIC_${variable}}")
        unset(${variable} CACHE)
        unset(${variable})
    endif()
endforeach()
erlang_aot_probe_zlib()
if(NOT ZLIB_FOUND AND WIN32 AND ERLANG_AOT_DOWNLOAD_ZLIB)
    erlang_aot_build_zlib(prefix)
    set(ZLIB_INCLUDE_DIR "${prefix}/include" CACHE PATH "zlib headers" FORCE)
    set(ZLIB_LIBRARY_DEBUG "${prefix}/lib/zsd.lib" CACHE FILEPATH "Debug zlib" FORCE)
    set(ZLIB_LIBRARY_RELEASE "${prefix}/lib/zs.lib" CACHE FILEPATH "Release zlib" FORCE)
    foreach(variable IN ITEMS ZLIB_INCLUDE_DIR ZLIB_LIBRARY_DEBUG ZLIB_LIBRARY_RELEASE)
        set(ERLANG_AOT_AUTOMATIC_${variable} "${${variable}}" CACHE INTERNAL "Automatic zlib selection" FORCE)
    endforeach()
endif()
include("${CMAKE_ROOT}/Modules/FindZLIB.cmake")
