# LLVM calls FindZLIB while loading its package; keep the fallback local to that search.
include("${CMAKE_CURRENT_LIST_DIR}/../ZlibDependencies.cmake")
if(CLAUSE_ZLIB_ROOT_HINT)
    set(ZLIB_ROOT "${CLAUSE_ZLIB_ROOT_HINT}")
endif()
# Re-evaluate automatic builds when the parent toolchain or LLVM CRT choice changes.
foreach(variable IN ITEMS ZLIB_INCLUDE_DIR ZLIB_LIBRARY_DEBUG ZLIB_LIBRARY_RELEASE)
    if(DEFINED CLAUSE_AUTOMATIC_${variable} AND "${${variable}}" STREQUAL "${CLAUSE_AUTOMATIC_${variable}}")
        unset(${variable} CACHE)
        unset(${variable})
    endif()
endforeach()
# CMake's builtin finder adds .a suffixes even for MSVC; resolve libraries before invoking it.
find_path(ZLIB_INCLUDE_DIR zlib.h HINTS "${ZLIB_ROOT}" ENV ZLIB_ROOT PATH_SUFFIXES include)
find_library(ZLIB_LIBRARY_RELEASE NAMES zs zlibstatic zlibstat zlib z
    HINTS "${ZLIB_ROOT}" ENV ZLIB_ROOT PATH_SUFFIXES lib)
find_library(ZLIB_LIBRARY_DEBUG NAMES zsd zlibstaticd zlibstatd zlibd zd
    HINTS "${ZLIB_ROOT}" ENV ZLIB_ROOT PATH_SUFFIXES lib)
if(NOT ZLIB_INCLUDE_DIR OR NOT (ZLIB_LIBRARY_RELEASE OR ZLIB_LIBRARY_DEBUG))
    if(NOT CLAUSE_DOWNLOAD_ZLIB)
        message(FATAL_ERROR "zlib is required by LLVM. Set ZLIB_ROOT to an MSVC installation or enable CLAUSE_DOWNLOAD_ZLIB.")
    endif()
    clause_build_zlib(prefix)
    set(ZLIB_INCLUDE_DIR "${prefix}/include" CACHE PATH "zlib headers" FORCE)
    set(ZLIB_LIBRARY_DEBUG "${prefix}/lib/zsd.lib" CACHE FILEPATH "Debug zlib" FORCE)
    set(ZLIB_LIBRARY_RELEASE "${prefix}/lib/zs.lib" CACHE FILEPATH "Release zlib" FORCE)
    foreach(variable IN ITEMS ZLIB_INCLUDE_DIR ZLIB_LIBRARY_DEBUG ZLIB_LIBRARY_RELEASE)
        set(CLAUSE_AUTOMATIC_${variable} "${${variable}}" CACHE INTERNAL "Automatic zlib selection" FORCE)
    endforeach()
endif()
include(SelectLibraryConfigurations)
select_library_configurations(ZLIB)
include("${CMAKE_ROOT}/Modules/FindZLIB.cmake")
