cmake_minimum_required(VERSION 3.25)
# Analyze project translation units using the configured compiler flags.
get_filename_component(project_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED QUALITY_BUILD_DIR)
    set(QUALITY_BUILD_DIR "${project_root}/build/debug")
endif()
set(database "${QUALITY_BUILD_DIR}/compile_commands.json")
if(NOT EXISTS "${database}")
    message(FATAL_ERROR "Missing ${database}. Configure a Makefiles or Ninja build first.")
endif()
include("${QUALITY_BUILD_DIR}/QualityToolchain.cmake")
get_filename_component(clang_directory "${quality_clang}" DIRECTORY)
find_program(CLANG_TIDY_EXECUTABLE NAMES clang-tidy
    HINTS "${project_root}/.venv-quality/bin" "${project_root}/.venv-quality/Scripts"
        "${clang_directory}"
    REQUIRED
)
set(toolchain_args)
if(quality_frontend STREQUAL "MSVC")
    list(APPEND quality_implicit_includes ${quality_msvc_includes})
endif()
list(REMOVE_DUPLICATES quality_implicit_includes)
foreach(directory IN LISTS quality_implicit_includes)
    if(quality_frontend STREQUAL "MSVC")
        list(APPEND toolchain_args "--extra-arg=/imsvc${directory}")
    else()
        list(APPEND toolchain_args "--extra-arg=-isystem${directory}")
    endif()
endforeach()
if(quality_apple_sysroot)
    list(APPEND toolchain_args --extra-arg=-isysroot "--extra-arg=${quality_apple_sysroot}")
endif()

file(READ "${database}" commands)
string(JSON command_count LENGTH "${commands}")
if(command_count EQUAL 0)
    message(FATAL_ERROR "The compilation database is empty.")
endif()
math(EXPR last_command "${command_count} - 1")
set(sources)
set(selected_commands "[")
set(separator "")
foreach(index RANGE ${last_command})
    string(JSON source GET "${commands}" ${index} file)
    string(JSON directory GET "${commands}" ${index} directory)
    get_filename_component(source "${source}" ABSOLUTE BASE_DIR "${directory}")
    file(RELATIVE_PATH relative "${project_root}" "${source}")
    if(relative MATCHES "^(compiler|runtime|abi)/")
        list(APPEND sources "${source}")
        string(JSON entry GET "${commands}" ${index})
        string(APPEND selected_commands "${separator}${entry}")
        set(separator ",")
    endif()
endforeach()
list(REMOVE_DUPLICATES sources)
if(NOT sources)
    message(FATAL_ERROR "No project translation units found in ${database}.")
endif()

# Run the same translation units/flags independently with LLVM's bounded parallel runner.
find_program(RUN_CLANG_TIDY_EXECUTABLE NAMES run-clang-tidy run-clang-tidy.py
    HINTS "${project_root}/.venv-quality/bin" "${project_root}/.venv-quality/Scripts"
        "${clang_directory}" REQUIRED)
cmake_host_system_information(RESULT quality_cpus QUERY NUMBER_OF_LOGICAL_CORES)
if(NOT DEFINED QUALITY_JOBS)
    set(QUALITY_JOBS "${quality_cpus}")
endif()
if(NOT QUALITY_JOBS MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "QUALITY_JOBS must be a positive integer.")
endif()
if(QUALITY_JOBS GREATER 6)
    set(QUALITY_JOBS 6)
endif()
# Preserve every selected command verbatim, including its original working directory.
set(selected_database "${QUALITY_BUILD_DIR}/quality")
file(MAKE_DIRECTORY "${selected_database}")
file(WRITE "${selected_database}/compile_commands.json" "${selected_commands}]")
list(TRANSFORM toolchain_args REPLACE "^--extra-arg=" "-extra-arg=")
list(LENGTH sources source_count)
message(STATUS "Analyzing all ${source_count} production translation units (${QUALITY_JOBS} concurrent jobs)")
execute_process(
    COMMAND "${RUN_CLANG_TIDY_EXECUTABLE}" "-p=${selected_database}" "-j=${QUALITY_JOBS}"
        "-clang-tidy-binary=${CLANG_TIDY_EXECUTABLE}" "-config-file=${project_root}/.clang-tidy" ${toolchain_args}
    WORKING_DIRECTORY "${project_root}"
    RESULT_VARIABLE tidy_result
)
if(NOT tidy_result STREQUAL "0")
    message(FATAL_ERROR "clang-tidy failed. Fix the diagnostics above before committing.")
endif()
