# Host SDK dependency used only by the compiler's private LLVM boundary.
include_guard(GLOBAL)
# Installed LLVM packages may probe C dependencies such as LibEdit.
enable_language(C)
include("${CMAKE_CURRENT_LIST_DIR}/LLVMPolicy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/LLVMDownloads.cmake")
option(ERLANG_AOT_DOWNLOAD_LLVM "Download a pinned LLVM SDK into thirdparty when no global SDK is found" ON)

# Prefer explicit installations, then global packages, then the shared verified download.
function(erlang_aot_select_llvm)
    if(WIN32)
        list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/modules")
        set(ERLANG_AOT_ZLIB_ROOT_HINT "${ZLIB_ROOT}")
    endif()
    # CMake caches automatic discoveries; recheck global installs on subsequent configurations.
    if(LLVM_DIR AND LLVM_DIR STREQUAL ERLANG_AOT_LLVM_AUTOMATIC_DIR)
        unset(LLVM_DIR CACHE)
        unset(LLVM_DIR)
    endif()
    if(NOT LLVM_DIR AND DEFINED ENV{LLVM_DIR})
        set(LLVM_DIR "$ENV{LLVM_DIR}")
    endif()
    if(LLVM_DIR)
        erlang_aot_check_llvm_location("${LLVM_DIR}")
        if(NOT EXISTS "${LLVM_DIR}/LLVMConfig.cmake")
            message(FATAL_ERROR "LLVM 23.1.x >=23.1.1 SDK package missing at LLVM_DIR=${LLVM_DIR}; no fallback for an explicit selection.")
        endif()
        find_package(LLVM 23.1.1 REQUIRED CONFIG GLOBAL PATHS "${LLVM_DIR}" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
    else()
        erlang_aot_llvm_search_paths(search_paths)
        message(STATUS "LLVM 23.1.x >=23.1.1 global SDK search: ${search_paths}")
        find_package(LLVM 23.1.1 QUIET CONFIG GLOBAL PATHS ${search_paths} NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(NOT LLVM_FOUND)
            if(NOT ERLANG_AOT_DOWNLOAD_LLVM)
                message(FATAL_ERROR "No global LLVM 23.1.x SDK found and ERLANG_AOT_DOWNLOAD_LLVM is OFF. Set LLVM_DIR or enable SDK downloads.")
            endif()
            erlang_aot_download_llvm(sdk_directory)
            set(LLVM_DIR "${sdk_directory}")
            set(ERLANG_AOT_DOWNLOADED_LLVM TRUE)
            set(ERLANG_AOT_DOWNLOADED_LLVM TRUE PARENT_SCOPE)
            find_package(LLVM 23.1.1 REQUIRED CONFIG GLOBAL PATHS "${sdk_directory}" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        endif()
        set(ERLANG_AOT_LLVM_AUTOMATIC_DIR "${LLVM_DIR}" CACHE INTERNAL "Last automatically selected LLVM SDK" FORCE)
    endif()
    # Export package variables to the private SDK boundary without leaking them to project targets.
    get_cmake_property(variables VARIABLES)
    foreach(variable IN LISTS variables)
        if(variable MATCHES "^LLVM_")
            set(${variable} "${${variable}}" PARENT_SCOPE)
        endif()
    endforeach()
endfunction()

# Confine package variables (including CRT/module-path settings) to this function.
function(erlang_aot_find_llvm)
    erlang_aot_select_llvm()
    erlang_aot_check_llvm_location("${LLVM_DIR}")
    erlang_aot_check_llvm_location("${LLVM_INSTALL_PREFIX}")
    erlang_aot_check_llvm_version("${LLVM_PACKAGE_VERSION}")
    if(NOT EXISTS "${LLVM_INSTALL_PREFIX}/include/llvm/Config/llvm-config.h")
        message(FATAL_ERROR "LLVM SDK installation is incomplete: ${LLVM_INSTALL_PREFIX}")
    endif()

    add_library(erlang_llvm_sdk INTERFACE IMPORTED GLOBAL)
    # Official Windows SDK archives use the release static CRT and unchecked STL in every configuration.
    if(ERLANG_AOT_DOWNLOADED_LLVM AND WIN32)
        if(ERLANG_AOT_DEFAULT_MSVC_RUNTIME)
            set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded)
            set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded PARENT_SCOPE)
        endif()
        if(ERLANG_AOT_MSVC_ITERATOR_DEBUG_LEVEL STREQUAL "")
            set(ERLANG_AOT_MSVC_ITERATOR_DEBUG_LEVEL 0 PARENT_SCOPE)
        endif()
        set_property(TARGET erlang_llvm_sdk APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS _ITERATOR_DEBUG_LEVEL=0)
        message(STATUS "Downloaded Windows LLVM SDK: /MT and _ITERATOR_DEBUG_LEVEL=0 required, including Debug")
    endif()
    # Match LLVM's RTTI setting only at its private boundary; frontend/runtime RTTI and exceptions stay enabled.
    if(NOT LLVM_ENABLE_RTTI)
        if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
            set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_COMPILE_OPTIONS /GR-)
        else()
            set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_COMPILE_OPTIONS -fno-rtti)
        endif()
    endif()
    set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${LLVM_INCLUDE_DIRS}")
    set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${LLVM_INCLUDE_DIRS}")
    separate_arguments(definitions NATIVE_COMMAND "${LLVM_DEFINITIONS}")
    list(TRANSFORM definitions REPLACE "^-D" "")
    set_property(TARGET erlang_llvm_sdk APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS "${definitions}")
    # Initialize/link only project backends present in this installed SDK.
    set(backends)
    set(components Core Support Target TransformUtils CodeGen MC Object)
    foreach(backend IN ITEMS X86 ARM AArch64)
        if(backend IN_LIST LLVM_TARGETS_TO_BUILD)
            list(APPEND backends "${backend}")
            list(APPEND components "${backend}CodeGen" "${backend}Desc" "${backend}Info" "${backend}AsmParser")
        endif()
    endforeach()
    set_property(TARGET erlang_llvm_sdk PROPERTY ERLANG_AOT_LLVM_BACKENDS "${backends}")
    if(LLVM_LINK_LLVM_DYLIB AND TARGET LLVM)
        set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_LINK_LIBRARIES LLVM)
    else()
        llvm_map_components_to_libnames(libraries ${components})
        set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_LINK_LIBRARIES "${libraries}")
    endif()

    # Use real C++ objects to detect host architecture/stdlib/CRT and header-library mismatches.
    include(CheckCXXSourceCompiles)
    file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/probes/llvm.cpp" probe)
    set(CMAKE_REQUIRED_LIBRARIES erlang_llvm_sdk)
    unset(ERLANG_AOT_LLVM_LINKS CACHE)
    check_cxx_source_compiles("${probe}" ERLANG_AOT_LLVM_LINKS)
    if(NOT ERLANG_AOT_LLVM_LINKS)
        message(FATAL_ERROR "LLVM SDK cannot link with this C++23 host toolchain. Check architecture, libc++/libstdc++ or CRT, RTTI and exceptions; see CMakeConfigureLog.yaml.")
    endif()
    message(STATUS "LLVM ${LLVM_PACKAGE_VERSION}: ${LLVM_INSTALL_PREFIX} (host ${LLVM_HOST_TRIPLE}; backends ${LLVM_TARGETS_TO_BUILD})")
    set_property(TARGET erlang_llvm_sdk PROPERTY ERLANG_AOT_LLVM_CMAKE_DIR "${LLVM_DIR}")
    set(ERLANG_AOT_LLVM_VERSION "${LLVM_PACKAGE_VERSION}" PARENT_SCOPE)
    set(ERLANG_AOT_LLVM_PREFIX "${LLVM_INSTALL_PREFIX}" PARENT_SCOPE)
    set(ERLANG_AOT_LLVM_CMAKE_DIR "${LLVM_DIR}" PARENT_SCOPE)
endfunction()

erlang_aot_find_llvm()
