# Host SDK dependency used only by the compiler's private LLVM boundary.
include_guard(GLOBAL)
# Installed LLVM packages may probe C dependencies such as LibEdit.
enable_language(C)
include("${CMAKE_CURRENT_LIST_DIR}/LLVMPolicy.cmake")

# Confine package variables (including CRT/module-path settings) to this function.
function(erlang_aot_find_llvm)
    if(NOT LLVM_DIR AND DEFINED ENV{LLVM_DIR})
        set(LLVM_DIR "$ENV{LLVM_DIR}")
    endif()
    if(LLVM_DIR)
        erlang_aot_check_llvm_location("${LLVM_DIR}")
        if(NOT EXISTS "${LLVM_DIR}/LLVMConfig.cmake")
            message(FATAL_ERROR "LLVM 23.1.x >=23.1.1 SDK package missing at LLVM_DIR=${LLVM_DIR}; no fallback.")
        endif()
        set(search_paths "${LLVM_DIR}")
    else()
        erlang_aot_llvm_search_paths(search_paths)
    endif()
    message(STATUS "LLVM 23.1.x >=23.1.1 global SDK search: ${search_paths}")
    # NO_DEFAULT_PATH excludes environment prefixes, package registries and private SDK hints.
    find_package(LLVM 23.1.1 REQUIRED CONFIG GLOBAL PATHS ${search_paths} NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
    erlang_aot_check_llvm_location("${LLVM_DIR}")
    erlang_aot_check_llvm_location("${LLVM_INSTALL_PREFIX}")
    erlang_aot_check_llvm_version("${LLVM_PACKAGE_VERSION}")
    if(NOT LLVM_ENABLE_RTTI)
        message(FATAL_ERROR "The initial LLVM SDK contract requires RTTI enabled; project RTTI will not be disabled.")
    endif()
    if(NOT EXISTS "${LLVM_INSTALL_PREFIX}/include/llvm/Config/llvm-config.h")
        message(FATAL_ERROR "LLVM SDK installation is incomplete: ${LLVM_INSTALL_PREFIX}")
    endif()

    add_library(erlang_llvm_sdk INTERFACE IMPORTED GLOBAL)
    set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${LLVM_INCLUDE_DIRS}")
    set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${LLVM_INCLUDE_DIRS}")
    separate_arguments(definitions NATIVE_COMMAND "${LLVM_DEFINITIONS}")
    list(TRANSFORM definitions REPLACE "^-D" "")
    set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_COMPILE_DEFINITIONS "${definitions}")
    # Initialize/link only project backends present in this installed SDK.
    set(backends)
    set(components Core Support Target TransformUtils CodeGen MC Object)
    foreach(backend IN ITEMS X86 ARM AArch64)
        if(backend IN_LIST LLVM_TARGETS_TO_BUILD)
            list(APPEND backends "${backend}")
            list(APPEND components "${backend}CodeGen" "${backend}Desc" "${backend}Info" "${backend}AsmParser")
        endif()
    endforeach()
    set_property(TARGET erlang_llvm_sdk PROPERTY ERLANG_AOT_LLVM_BACKENDS "${backends}")
    if(LLVM_LINK_LLVM_DYLIB AND TARGET LLVM)
        set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_LINK_LIBRARIES LLVM)
    else()
        llvm_map_components_to_libnames(libraries ${components})
        set_property(TARGET erlang_llvm_sdk PROPERTY INTERFACE_LINK_LIBRARIES "${libraries}")
    endif()

    # Use real C++ objects to detect host architecture/stdlib/CRT and header-library mismatches.
    include(CheckCXXSourceCompiles)
    file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/probes/llvm.cpp" probe)
    set(CMAKE_REQUIRED_LIBRARIES erlang_llvm_sdk)
    unset(ERLANG_AOT_LLVM_LINKS CACHE)
    check_cxx_source_compiles("${probe}" ERLANG_AOT_LLVM_LINKS)
    if(NOT ERLANG_AOT_LLVM_LINKS)
        message(FATAL_ERROR "LLVM SDK cannot link with this C++23 host toolchain. Check architecture, libc++/libstdc++ or CRT, RTTI and exceptions; see CMakeConfigureLog.yaml.")
    endif()
    message(STATUS "LLVM ${LLVM_PACKAGE_VERSION}: ${LLVM_INSTALL_PREFIX} (host ${LLVM_HOST_TRIPLE}; backends ${LLVM_TARGETS_TO_BUILD})")
    set_property(TARGET erlang_llvm_sdk PROPERTY ERLANG_AOT_LLVM_CMAKE_DIR "${LLVM_DIR}")
    set(ERLANG_AOT_LLVM_VERSION "${LLVM_PACKAGE_VERSION}" PARENT_SCOPE)
    set(ERLANG_AOT_LLVM_PREFIX "${LLVM_INSTALL_PREFIX}" PARENT_SCOPE)
    set(ERLANG_AOT_LLVM_CMAKE_DIR "${LLVM_DIR}" PARENT_SCOPE)
endfunction()

erlang_aot_find_llvm()
