include("${HOST_SETTINGS}")
if(NOT DEFINED INPUT_ROOT)
    set(INPUT_ROOT "${SOURCE_ROOT}/tests/fixtures/codegen/native")
endif()
set(object_dir "${TEST_DIR}/positional-objects")
if(PROJECT_MODE)
    set(object_dir "${TEST_DIR}/project-objects")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}/source")
set(inputs "${INPUT_ROOT}/answer.erl" "${INPUT_ROOT}/client.erl")
if(PROJECT_MODE)
    set(inputs --project "${INPUT_ROOT}/native-project.toml")
endif()
execute_process(COMMAND "${TOOL}" -${OPTIMIZATION} ${EXTRA_OPTIONS} --emit obj
    --artifact-dir "${object_dir}" ${inputs}
    RESULT_VARIABLE emitted OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 60)
if(NOT emitted STREQUAL "0" OR NOT output STREQUAL "")
    message(FATAL_ERROR "CLI emission failed: ${emitted}: ${output}${errors}")
endif()
file(GLOB objects "${object_dir}/*.o" "${object_dir}/*.obj" "${object_dir}/*/*.o" "${object_dir}/*/*.obj")
list(LENGTH objects count)
if(NOT count EQUAL 2)
    message(FATAL_ERROR "Expected two separately linkable objects: ${objects}")
endif()
file(WRITE "${TEST_DIR}/source/empty.cpp" "int main() { return 0; }\n")
file(WRITE "${TEST_DIR}/source/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.28)
project(GeneratedConsumer LANGUAGES CXX)
if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "The native harness requires the configured Clang driver")
endif()
# Link the runtime the parent build already compiled (Clause::generated_program).
include("${RUNTIME_TARGETS}")
add_executable(linked "${SOURCE_ROOT}/tests/compiler/codegen/native_consumer.cpp" ${OBJECTS})
target_link_libraries(linked PRIVATE Clause::generated_program)
set_target_properties(linked PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/$<CONFIG>")
add_executable(unlinked EXCLUDE_FROM_ALL empty.cpp ${OBJECTS})
]=])
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_DIR}/source" -B "${TEST_DIR}/build"
    "-DSOURCE_ROOT=${SOURCE_ROOT}" "-DOBJECTS=${objects}" ${host_configure_args}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native configure: ${output}${errors}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_DIR}/build" --config "${HOST_CONFIG}" --target linked
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native link: ${output}${errors}")
endif()
file(READ "${INPUT_ROOT}/expected.txt" expected)
string(REPLACE "\r\n" "\n" expected "${expected}")
foreach(repeat RANGE 1 2)
    execute_process(COMMAND "${TEST_DIR}/build/bin/${HOST_CONFIG}/linked${HOST_SUFFIX}"
        INPUT_FILE "${INPUT_ROOT}/calls.txt" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result STREQUAL "0" OR NOT output STREQUAL expected OR NOT errors STREQUAL "")
        message(FATAL_ERROR "Native execution ${repeat}: ${result}\nExpected:\n${expected}\nActual:\n${output}\n${errors}")
    endif()
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_DIR}/build" --config "${HOST_CONFIG}" --target unlinked
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(result STREQUAL "0" OR NOT "${output}${errors}" MATCHES "CLAUSE_register_module_v4")
    message(FATAL_ERROR "Missing runtime did not fail at the ABI reference: ${output}${errors}")
endif()
