include("${HOST_SETTINGS}")
if(NOT DEFINED INPUT_ROOT)
    set(INPUT_ROOT "${SOURCE_ROOT}/tests/fixtures/codegen/native")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}/source")
execute_process(COMMAND "${TOOL}" -${OPTIMIZATION} ${EXTRA_OPTIONS} --emit obj
    --artifact-dir "${TEST_DIR}/objects" "${INPUT_ROOT}/answer.erl" "${INPUT_ROOT}/client.erl"
    RESULT_VARIABLE emitted OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 60)
if(NOT emitted STREQUAL "0" OR NOT output STREQUAL "")
    message(FATAL_ERROR "CLI emission failed: ${emitted}: ${output}${errors}")
endif()
file(GLOB objects "${TEST_DIR}/objects/*.o" "${TEST_DIR}/objects/*.obj")
list(LENGTH objects count)
if(NOT count EQUAL 2)
    message(FATAL_ERROR "Expected two separately linkable objects: ${objects}")
endif()
file(WRITE "${TEST_DIR}/source/empty.cpp" "int main() { return 0; }\n")
file(WRITE "${TEST_DIR}/source/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.28)
project(GeneratedConsumer LANGUAGES CXX)
if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "The native harness requires the configured Clang driver")
endif()
set(ERLANG_AOT_BUILD_COMPILER OFF CACHE BOOL "" FORCE)
set(ERLANG_AOT_BUILD_RUNTIME ON CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
add_subdirectory("${SOURCE_ROOT}" runtime-build)
if(TARGET erlang_llvm_sdk)
    message(FATAL_ERROR "Native consumer acquired LLVM")
endif()
add_executable(linked "${SOURCE_ROOT}/tests/compiler/codegen/native_consumer.cpp" ${OBJECTS})
target_link_libraries(linked PRIVATE ErlangAoT::generated_program)
set_target_properties(linked PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/$<CONFIG>")
add_executable(unlinked EXCLUDE_FROM_ALL empty.cpp ${OBJECTS})
]=])
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_DIR}/source" -B "${TEST_DIR}/build"
    "-DSOURCE_ROOT=${SOURCE_ROOT}" "-DOBJECTS=${objects}" ${host_configure_args}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native configure: ${output}${errors}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_DIR}/build" --config "${HOST_CONFIG}" --target linked
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Native link: ${output}${errors}")
endif()
file(READ "${INPUT_ROOT}/expected.txt" expected)
string(REPLACE "\r\n" "\n" expected "${expected}")
foreach(repeat RANGE 1 2)
    execute_process(COMMAND "${TEST_DIR}/build/bin/${HOST_CONFIG}/linked${HOST_SUFFIX}"
        INPUT_FILE "${INPUT_ROOT}/calls.txt" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
    string(REPLACE "\r\n" "\n" output "${output}")
    if(NOT result STREQUAL "0" OR NOT output STREQUAL expected OR NOT errors STREQUAL "")
        message(FATAL_ERROR "Native execution ${repeat}: ${result}\nExpected:\n${expected}\nActual:\n${output}\n${errors}")
    endif()
endforeach()
execute_process(COMMAND "${TEST_DIR}/build/bin/${HOST_CONFIG}/linked${HOST_SUFFIX}" --deferred-allocation
    INPUT_FILE "${INPUT_ROOT}/calls.txt" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
string(REPLACE "\r\n" "\n" output "${output}")
string(REPLACE "\r\n" "\n" errors "${errors}")
if(NOT result STREQUAL "1" OR NOT output STREQUAL expected OR
        NOT errors STREQUAL "[allocation] notimpl [operation=\"ProcessHeap::allocate\"]\n")
    message(FATAL_ERROR "Deferred allocation did not fail cleanly before generated execution/teardown: ${result}: ${output}${errors}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_DIR}/build" --config "${HOST_CONFIG}" --target unlinked
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(result STREQUAL "0" OR NOT "${output}${errors}" MATCHES "erlang_aot_register_module_v2")
    message(FATAL_ERROR "Missing runtime did not fail at the ABI reference: ${output}${errors}")
endif()
