file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
file(WRITE "${TEST_DIR}/one.erl" "-module(one). -export([value/0]). value() -> 42.\n")
file(WRITE "${TEST_DIR}/project.toml" "schema_version=1\n[[targets]]\nname='one'\nsources=['one.erl']\n")
# Exercise public option validation without relying on private option storage.
function(check code pattern)
    execute_process(COMMAND "${TOOL}" ${ARGN} WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
    if(NOT "${result}" STREQUAL "${code}" OR NOT err MATCHES "${pattern}")
        message(FATAL_ERROR "${ARGN}: exit=${result}, stdout=[${out}], stderr=[${err}]")
    endif()
endfunction()
foreach(option IN ITEMS --emit --artifact-dir --target-triple)
    check(2 "expected a value" ${option})
    check(2 "expected a value" ${option} "")
endforeach()
check(2 "expects obj" --emit executable one.erl)
check(2 "more than once" --emit obj --emit llvm-ir one.erl)
check(2 "more than once" --artifact-dir a --artifact-dir b --emit obj one.erl)
check(2 "more than once" --target-triple x86_64-pc-windows-msvc --target-triple aarch64-linux-gnu one.erl)
check(2 "more than once" -O0 -O2 one.erl)
check(2 "more than once" -O2 -O2 one.erl)
check(2 "requires --emit" --artifact-dir artifacts one.erl)
check(2 "cannot be combined" --emit obj --output executable one.erl)
foreach(action IN ITEMS --preprocess-check --parse-check --print-pp --print-ast)
    foreach(switch IN ITEMS -O0 -O2 --no-type-specialization)
        check(2 "compilation switches" ${action} ${switch} missing.erl)
    endforeach()
    check(2 "compilation switches" ${action} --emit llvm-ir missing.erl)
    check(2 "compilation switches" ${action} --target-triple x86_64-linux-gnu missing.erl)
endforeach()
check(2 "compilation switches" --new-project new -O2)
check(0 "^$" --help --emit obj --artifact-dir nowhere --target-triple invalid missing.erl)
check(0 "^$" --version --project missing.toml -O2)
foreach(level IN ITEMS -O0 -O2)
    check(0 "^$" ${level} one.erl)
    check(0 "^$" --no-type-specialization ${level} one.erl)
    check(0 "^$" ${level} --no-type-specialization --project project.toml --target one)
endforeach()
if(EXISTS "${TEST_DIR}/build" OR EXISTS "${TEST_DIR}/artifacts" OR EXISTS "${TEST_DIR}/nowhere" OR EXISTS "${TEST_DIR}/new.toml")
    message(FATAL_ERROR "Option-only/default requests created artifacts")
endif()
