file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}/source space")
file(COPY "${FIXTURES}/answer.erl" "${FIXTURES}/client.erl" DESTINATION "${TEST_DIR}/source space")
# Preserve explicit subprocess outcomes and keep product stdout silent for compilation.
function(check code pattern)
    execute_process(COMMAND "${TOOL}" ${ARGN} WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    if(NOT "${result}" STREQUAL "${code}" OR NOT out STREQUAL "" OR NOT err MATCHES "${pattern}")
        message(FATAL_ERROR "${ARGN}: exit=${result} stdout=[${out}] stderr=[${err}]")
    endif()
endfunction()
set(answer "source space/answer.erl")
set(client "source space/client.erl")
check(0 "^$" "${client}" "${answer}")
if(EXISTS "${TEST_DIR}/build")
    message(FATAL_ERROR "Default in-memory compilation wrote files")
endif()
foreach(level IN ITEMS -O0 -O2)
    foreach(kind IN ITEMS obj llvm-ir llvm-bc)
        set(root "${TEST_DIR}/artifacts/${level}/${kind}")
        check(0 "^$" ${level} --emit ${kind} --artifact-dir "${root}" "${client}" "${answer}")
        file(GLOB outputs "${root}/*")
        list(LENGTH outputs count)
        if(NOT count EQUAL 2)
            message(FATAL_ERROR "Expected one artifact per module: ${outputs}")
        endif()
        foreach(output IN LISTS outputs)
            file(SIZE "${output}" size)
            if(size EQUAL 0)
                message(FATAL_ERROR "Empty artifact")
            endif()
        endforeach()
    endforeach()
endforeach()
file(READ "${TEST_DIR}/artifacts/-O0/llvm-ir/eav1_616e73776572__0.ll" ir)
if(NOT ir MATCHES "define i64 @eav1_616e73776572_76616c7565_0" OR NOT ir MATCHES "ret i64 687" OR NOT ir MATCHES "erlang_aot_register_module_v2")
    message(FATAL_ERROR "Missing value/ABI/runtime structures: ${ir}")
endif()
file(READ "${TEST_DIR}/artifacts/-O0/llvm-bc/eav1_616e73776572__0.bc" magic LIMIT 4 HEX)
if(NOT magic STREQUAL "4243c0de")
    message(FATAL_ERROR "Output is not LLVM bitcode: ${magic}")
endif()
check(0 "^$" --emit llvm-ir "${answer}")
set(preserved "${TEST_DIR}/build/aot/eav1_616e73776572__0.ll")
file(READ "${preserved}" before)
file(WRITE "${TEST_DIR}/bad.erl" "-module(bad). value() -> [1].\n")
check(1 "notimpl" --emit llvm-ir "${answer}" bad.erl)
file(READ "${preserved}" after)
if(NOT before STREQUAL after OR EXISTS "${TEST_DIR}/build/aot/eav1_626164__0.ll")
    message(FATAL_ERROR "Failed batch published artifacts")
endif()
file(WRITE "${TEST_DIR}/bad.erl" "-module(bad). value( -> 1.\n")
check(1 "error" --emit llvm-ir --artifact-dir syntax-failure "${answer}" bad.erl)
if(EXISTS "${TEST_DIR}/syntax-failure")
    message(FATAL_ERROR "Parse failure entered artifact publication")
endif()
check(1 "duplicate module" --emit llvm-ir --artifact-dir duplicates "${answer}" "${answer}")
check(1 "target architecture" --target-triple invalid --emit obj --artifact-dir invalid-target "${answer}")
file(MAKE_DIRECTORY "${TEST_DIR}/alias")
file(CREATE_LINK "${TEST_DIR}/${answer}" "${TEST_DIR}/alias/eav1_616e73776572__0.ll" RESULT linked)
if(NOT linked STREQUAL "0")
    message(FATAL_ERROR "Cannot create hard-link alias fixture: ${linked}")
endif()
check(1 "aliases an input" --emit llvm-ir --artifact-dir alias "${answer}")
file(WRITE "${TEST_DIR}/source space/quoted.erl" "-module('../strange'). -export([value/0]). value() -> -1.\n")
check(0 "^$" --emit llvm-ir --artifact-dir "unicode å" "source space/quoted.erl")
if(NOT EXISTS "${TEST_DIR}/unicode å/eav1_2e2e2f737472616e6765__0.ll")
    message(FATAL_ERROR "Module identity was not safely encoded")
endif()
