file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
file(WRITE "${TEST_DIR}/space å.erl" "-module(trace). -export([value/0,identity/1]). value() -> identity(42). identity(X) -> X.\n")
# Preserve both streams so phase order and stdout isolation are observable together.
function(run)
    execute_process(COMMAND "${TOOL}" ${ARGN} WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30 ENCODING UTF-8)
    if(NOT result EQUAL 0 OR NOT out STREQUAL "")
        message(FATAL_ERROR "Trace command failed: ${ARGN}: ${result}: ${out}${err}")
    endif()
    set(trace "${err}" PARENT_SCOPE)
endfunction()
run("space å.erl")
if(NOT trace STREQUAL "")
    message(FATAL_ERROR "Backend tracing was not opt-in")
endif()
run(--verbose -O2 "space å.erl")
set(previous -1)
foreach(phase IN ITEMS analysis calls declared-types inference contracts lowering specialization verification optimization emission)
    string(FIND "${trace}" "phase=${phase}" position)
    if(position LESS 0 OR position LESS previous)
        message(FATAL_ERROR "Missing/out-of-order phase ${phase}: ${trace}")
    endif()
    set(previous ${position})
endforeach()
if(NOT trace MATCHES "source=\"space å.erl\"" OR NOT trace MATCHES "skipped=no-benefit")
    message(FATAL_ERROR "Missing filename/profile reason: ${trace}")
endif()
run(--verbose -O2 --no-type-specialization "space å.erl")
if(NOT trace MATCHES "disabled-by-policy")
    message(FATAL_ERROR "Override omitted its reason")
endif()
run(--verbose --parse-check "space å.erl")
if(trace MATCHES "\\[comp\\]" OR NOT trace MATCHES "\\[pp\\].*\\[parse\\]")
    message(FATAL_ERROR "Frontend-only tracing changed: ${trace}")
endif()
run(--emit llvm-ir --artifact-dir plain "space å.erl")
run(--verbose --emit llvm-ir --artifact-dir traced "space å.erl")
file(SHA256 "${TEST_DIR}/plain/eav1_7472616365__0.ll" plain)
file(SHA256 "${TEST_DIR}/traced/eav1_7472616365__0.ll" traced)
if(NOT plain STREQUAL traced)
    message(FATAL_ERROR "Tracing altered emitted IR")
endif()
file(WRITE "${TEST_DIR}/control.erl" "-module('line\\nbreak'). value() -> 1.\n")
run(--verbose control.erl)
string(FIND "${trace}" "module=\"line\\x0abreak\"" escaped)
if(escaped LESS 0)
    message(FATAL_ERROR "Control characters injected trace lines: ${trace}")
endif()
file(WRITE "${TEST_DIR}/bad.erl" "-module(bad). value() -> [1].\n")
execute_process(COMMAND "${TOOL}" --verbose bad.erl WORKING_DIRECTORY "${TEST_DIR}"
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err ENCODING UTF-8)
if(result EQUAL 0 OR NOT out STREQUAL "" OR err MATCHES "phase=(inference|lowering|optimization|emission)")
    message(FATAL_ERROR "Failure traced phases that did not start: ${err}")
endif()
file(WRITE "${TEST_DIR}/project.toml" "schema_version=1\n[[targets]]\nname='one'\nsources=['space å.erl']\n[[targets]]\nname='two'\nsources=['space å.erl']\n")
run(--verbose --project project.toml --target two --target one)
string(FIND "${trace}" "target=\"two\"" two)
string(FIND "${trace}" "target=\"one\"" one)
if(two LESS 0 OR one LESS two)
    message(FATAL_ERROR "Project target trace order/context changed: ${trace}")
endif()
